### PR TITLE
Preserve RustPython History

### PR DESCRIPTION
**Pull request by MichaReiser**
## Summary

Follow up to #6099 that tries to preserve the history of the parser files

## Test Plan

Opening a file and showing blame shows past commits.

### CODE REVIEW

**Comment by MichaReiser** [comment]
Current dependencies on/for this PR:
* main
  * **PR #6119** <a href="https://app.graphite.dev/github/pr/astral-sh/ruff/6119" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/astral-sh/ruff/6119?utm_source=stack-comment).

**Comment by MichaReiser** [comment]
Important: Don't squash!

**Comment by Boshen** [comment]
I know you can do this in git, but damn your git foo is good!

**Comment by MichaReiser** [comment]
> I know you can do this in git, but damn your git foo is good!

You give me too much credit. I first messed it up in https://github.com/astral-sh/ruff/pull/6099 . I then followed [this guide](https://github.com/astral-sh/ruff/pull/6099#issuecomment-1653116497) that @davidszotten shared and had to give it like 5 tries to make it work... Let's hope it really works and that @charliermarsh doesn't kill me for doing a merge commit :sweat_smile:

**Comment by davidszotten** [comment]
🎉

**Comment by MichaReiser** [comment]
Lol, this didn't work. It worked when viewing the files on the branch but not after merging :confounded:

**Comment by MichaReiser** [comment]
I think I should have tone a rebase-merge rather than merge commit. Do I want to try this again

**Pull request merged**
