### PR TITLE
docs(options): fix some typos and improve consistency

### PR DESCRIPTION
**Pull request by mkniewallner**
## Summary

Fixes a few typos and consistency issues in the "Settings" documentation:
- use "Ruff" consistently in the few places where "ruff" is used
- use double quotes in the few places where single quotes are used
- add backticks around rule codes where they are currently missing
- update a few example values where they are the same as the defaults, for consistency

2nd commit might be controversial, as there are many options mentioned where we don't currently link to the documentation sections, so maybe it's done on purpose, as this will also appear in the JSON schema where it's not desirable? If that's the case, I can easily drop it.

## Test Plan

Local testing.

### CODE REVIEW

**Review by charliermarsh — APPROVED** [review]
Wow, this is excellent -- thank you! I skimmed through all the changes. How did you find these?

**Comment by charliermarsh** [comment]
> 2nd commit might be controversial, as there are many options mentioned where we don't currently link to the documentation sections, so maybe it's done on purpose, as this will also appear in the JSON schema where it's not desirable? If that's the case, I can easily drop it.

I think this _is_ true (that it will appear in the JSON Schema). But I think it's worth it.

**Comment by mkniewallner** [comment]
> Wow, this is excellent -- thank you! I skimmed through all the changes. How did you find these?

By manually skimming through the documentation (yeah, for real 😄).

**Comment by charliermarsh** [comment]
I'm very impressed, thanks!

**Pull request merged**
