### PR TITLE
Improve `type-name-incorrect-variance` message

### PR DESCRIPTION
**Pull request by tjkuson**
## Summary

Change the `type-name-incorrect-variance` diagnostic message to include the detected variance and a name change recommendation. For example,

```
`TypeVar` name "T_co" does not reflect its contravariance; consider renaming it to "T_contra"
```

Related to #5651.

## Test Plan

`cargo test`

### CODE REVIEW

**Comment by tjkuson** [comment]
I think something went wrong with GitHub Actions.

**Comment by charliermarsh** [comment]
What happens in the event that a variable is marked as both covariant and contravariant?

**Comment by tjkuson** [comment]
> What happens in the event that a variable is marked as both covariant and contravariant?

Currently, it ignores anything that is both covariant and contravariant. However, looking at the Pylint implementation, it emits

```
Type variable name does not reflect variance
```

It should be simple to emit a similar generic message. Do you think it's better to ignore invalid bivariant types or to emit a generic message instead?

**Comment by charliermarsh** [comment]
Hmm, I think ignoring them is fine actually, since this diagnostic can't actually be satisfied by renaming the variable.

**Pull request merged**
