### PR TITLE
Implement PYI047

### PR DESCRIPTION
**Pull request by LaBatata101**
## Summary

Checks for the presence of unused private `typing.TypeAlias` definitions.

ref #848 

## Test Plan

Snapshots and manual runs of flake8

### CODE REVIEW

**Review by zanieb — APPROVED** [review]
Thank you!

Since all the patterns were reviewed in https://github.com/astral-sh/ruff/pull/6098 this LGTM

**Review by zanieb — CHANGES_REQUESTED** [review]
Unfortunately it looks like those typeshed ecoystem changes are false positives e.g. https://github.com/python/typeshed/blob/852882b8bfe9e1792448b94809351a392e83ce9e/stdlib/_ast.pyi#L381-L385

cc @charliermarsh

**Comment by charliermarsh** [comment]
Yup easy to fix. Will chime in on how later.

**Comment by charliermarsh** [comment]
@LaBatata101 - Can you take a look at the refactor I did to the existing variants of these rules in https://github.com/astral-sh/ruff/pull/6142? In short, we should move them from the `bindings.rs` analyzer to the `deferred_scopes.rs` analyzer, so that they don't run on shadowed bindings.

**Comment by LaBatata101** [comment]
> @LaBatata101 - Can you take a look at the refactor I did to the existing variants of these rules in #6142? In short, we should move them from the `bindings.rs` analyzer to the `deferred_scopes.rs` analyzer, so that they don't run on shadowed bindings.

Looks great! Very good explanation too. 

I've already updated this PR and #6136

**Comment by zanieb** [comment]
It looks like the history is a little messed up here causing conflicts.

**Comment by LaBatata101** [comment]
> It looks like the history is a little messed up here causing conflicts.

Yeah... I don't really know what I did when I was pulling from upstream, everything went fine when I pulled on #6136.

I don't really know how to fix the history. 😅

**Comment by charliermarsh** [comment]
Haha. All good, I can figure out the history :)

**Review by charliermarsh — APPROVED** [review]

**Comment by charliermarsh** [comment]
Checked typeshed locally:

```console
/Users/crmarsh/workspace/typeshed/stubs/Pillow/PIL/_imaging.pyi:12:7: PYI046 Private protocol `_PixelAccessor` is never used
/Users/crmarsh/workspace/typeshed/stubs/bleach/bleach/callbacks.pyi:9:7: PYI046 Private protocol `_Callback` is never used
/Users/crmarsh/workspace/typeshed/stubs/openpyxl/openpyxl/xml/_functions_overloads.pyi:26:7: PYI046 Private protocol `_HasTagAndText` is never used
/Users/crmarsh/workspace/typeshed/stubs/openpyxl/openpyxl/xml/_functions_overloads.pyi:28:7: PYI046 Private protocol `_HasTagAndTextAndAttrib` is never used
Found 4 errors.
```

These all have `# noqa: Y046` on them, so they seem correct (since we use a different code for this rule).

**Pull request merged**
