### PR TITLE
Allow specification of `logging.Logger` re-exports via `logger-objects`

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

This PR adds a `logger-objects` setting that allows users to mark specific symbols a `logging.Logger` objects. Currently, if a `logger` is imported, we only flagged it as a `logging.Logger` if it comes exactly from the `logging` module or is `flask.current_app.logger`.

This PR allows users to mark specific loggers, like `logging_setup.logger`, to ensure that they're covered by the `flake8-logging-format` rules and others.

For example, if you have a module `logging_setup.py` with the following
contents:

```python
import logging

logger = logging.getLogger(__name__)
```

Adding `"logging_setup.logger"` to `logger-objects` will ensure that
`logging_setup.logger` is treated as a `logging.Logger` object when
imported from other modules (e.g., `from logging_setup import logger`).

Closes https://github.com/astral-sh/ruff/issues/5694.

### CODE REVIEW

**Comment by zanieb** [comment]
For what it's worth, these are false positives in cibuildwheel because they use a custom logger without deferred formatting https://github.com/pypa/cibuildwheel/blob/66b46d086804a9e9782354100d96a3a445431bca/cibuildwheel/logger.py

**Comment by charliermarsh** [comment]
Sadly those errors in cibuildwheel are false positives. They have a custom logger that matches our heuristic.

**Comment by zanieb** [comment]
It does seem weird to have this rule enabled at all if you are using a custom logger though

**Review by MichaReiser — APPROVED** [review]

**Comment by petermattia** [comment]
In our use case, we configure the standard logger in the package-level `__init.py__` and then import the configured `logger` object into our other modules. I imagine this use case is pretty common, but not positive.

**Comment by charliermarsh** [comment]
Yeah your use-case is very reasonable I think. The case I’m worried about is someone exporting something that matches the logger-like naming patterns we detect that isn’t actually a standard-library logger.

**Comment by petermattia** [comment]
Understood. How do you resolve situations like this? I suppose one option is to make the intended behavior configurable.

FWIW, I think the affected logging rules make sense for any logger, not just the standard library logger.

**Comment by charliermarsh** [comment]
What we may want to do for now is add a `logging-modules` setting similar to [`typing-modules`](https://beta.ruff.rs/docs/settings/#typing-modules) that lets you specify first-party modules that export loggers.

**Comment by petermattia** [comment]
That sounds perfect!

**Pull request merged**
