### PR TITLE
[`ruff`] Also report problems for `attrs` dataclasses in preview mode (`RUF008`, `RUF009`)

### LINKED ISSUE #9757: [FEATURE] Support attrs in RUF008 and RUF009
These rules guard against using mutable default values in `dataclasses`. It would be nice if these rules *also* supported attrs,  which is the (more feature-rich) predecessor which is also pretty widely used.

If this is something that you'd be open for, I think I can get some time to potentially contribute a patch myself.

### PR DESCRIPTION
**Pull request by InSyncWithFoo**
## Summary

Resolves #9757.

## Test Plan

`cargo nextest run` and `cargo insta test`.

### CODE REVIEW

**Comment by MichaReiser** [comment]
@AlexWaygood would you mind taking a look at this rule. I don't have the necessary context about what it changes to review it. 

I do think that we should make this a preview-only change because it increases the rule's scope.

**Review by AlexWaygood — APPROVED** [review]
Thanks @InSyncWithFoo, this is great! I pushed some changes:
- Optimised it a bit by adding some tracking to the semantic model of whether `attrs` has been imported or not
- Consolidated the logic in the `rules::ruff::helpers` module
- Made the change preview-only for now, since it increases the scope of the rule.

**Comment by pwuertz** [comment]
Note that `RUF009` can be a bit misleading when `auto_attribs=False` (or with older `attr.s` codebases):
```python
import attrs

@attrs.define(auto_attribs=False)
class X:
    a_field: int = attrs.field(default=42)
    not_a_field: list = (lambda: [])()
#                       ^^^^^^^^^^^^^^ RUF009 Do not perform function call in dataclass defaults
```
Without `auto_attribs`, `not_a_field` can't possibly be a  `dataclass` field. In this example, it's an incorrectly typed class variable. Fixing the typing error also fixes the `RUF009` warning:
```python
@attrs.define(auto_attribs=False)
class X:
    attrs_field: int = attrs.field(default=42)
    not_an_attrs_field: typing.ClassVar[list] = (lambda: [])()
```

**Comment by pwuertz** [comment]
This is an issue though when using `attrs.field` wrappers:

```python
def my_field():
    return attrs.field(default=42, metadata={'my_metadata': 42})


@attrs.define(auto_attribs=False)
class X:
    a_field: int = my_field()
#                  ^^^^^^^^^^ RUF009 Do not perform function call `my_field` in dataclass defaults
```

**Comment by MichaReiser** [comment]
> I can't get this working, even on 0.9.0 which was when this was merged:
> 
> ```
> ❯ cat tst.py
> import attrs
> 
> @attrs.deinfe
> class B :
>     mutable_default: list[int] = []
>     mutable_default2: list[int] = attrs.field(default=[])
> 
> ❯ uvx ruff@0.9.0 check --extend-select RUF008,B006 --preview -n --isolated  tst.py
> All checks passed!
> ```

Please open a new issue. It makes it easier to help and allows other users to find it too

**Pull request merged**
