### PR TITLE
Mark some `deprecated-import` fixes as unsafe

### LINKED ISSUE #7436: Split UP035 (deprecated-import) for aliases
I'd like to request the `deprecated-import` rule be split in two. Currently `UP035` flags two different kinds of deprecations:

- Names that have been moved, with a deprecated alias. Examples:
  - `collections.*` => `collections.abc.*`
  - `{pipes => shlex}.quote`
- Types that are deprecated, considered equivalent by type checkers, but are different runtime values.
  - This is everything in the `typing`, `typing_extensions` and `mypy_extensions` modules.

For the former group, fixing them is significantly safer, since the only visible side-effects would be that a module wasn't imported (in the case of `pipes`), and a lack of a `DeprecationWarning`. It'd be rare for code to depend on those side-effects. The latter group can potentially be an unsafe change if something tries to observe the types directly at runtime though.

Ultimately I'd like to be able to autofix the moved names, whilst being able to separately flag (with a suggested fix) the typing changes that would be observable at runtime.

### PR DESCRIPTION
**Pull request by tjkuson**
## Summary

Checked each import to see if its replacement is the same as the original. If the objects were different, marked the fix as unsafe.

Closes #7436.

## Test Plan

`cargo test`

### CODE REVIEW

**Review by zanieb — APPROVED** [review]
LGTM without actually checking each type

@charliermarsh want to review as well?

**Comment by charliermarsh** [comment]
@tjkuson - What was the methodology for determining whether the imports were the same, or changed?

**Comment by charliermarsh** [comment]
It may be challenging but... I feel like these could still be considered safe if the usages are exclusively in typing contexts / type annotations. What do you think?

**Comment by tjkuson** [comment]
> It may be challenging but... I feel like these could still be considered safe if the usages are exclusively in typing contexts / type annotations. What do you think?

As in making Ruff determine if an import is being used for typing only? There's already logic that checks if an import only used for typing, right? If so, it shouldn't be too difficult, unless I am missing something…

**Comment by zanieb** [comment]
@AlexWaygood are you interested in taking over review of this?

**Comment by AlexWaygood** [comment]
> @AlexWaygood are you interested in taking over review of this?

Sure, I'll take a look tomorrow

**Comment by charliermarsh** [comment]
I think I'm going to close this. I appreciate the work (thank you as always) and it's a reasonable proposal but ultimately I think it adds more overhead to the maintenance of the rule and to users than is worthwhile. If we see a real issue in practice from marking these as safe, I will of course revisit.

**Pull request closed without merging**
