### PR TITLE
Fix `F841` false negative on assignment to multiple variables

### LINKED ISSUE #8441: `F841` false negative on assignment to multiple variables
```py
def foo():
    a = bar() # error: F841
    b, c = bar() # no error

def bar():
    ...
```
[playground](https://play.ruff.rs/e10d4570-4368-4d83-af88-57b221fe899f)

### PR DESCRIPTION
**Pull request by tjkuson**
## Summary

Closes #8441 behind preview feature flag.

## Test Plan

`cargo test`

### CODE REVIEW

**Comment by tjkuson** [comment]
None of the new violations seem to be incorrect, but there are a lot of them. Moved the behaviour change behind the preview flag.

**Comment by tjkuson** [comment]
I don't know why there is a non-preview ecosystem change...

**Comment by T-256** [comment]
> I don't know why there is a non-preview ecosystem change...

rotki uses `preview = true` in `pyproject.toml`
I think there is problem `ruff_ecosystem` pacakge.
possible fix is adding `--force-no-preview` cli option.

**Comment by charliermarsh** [comment]
Thanks! Also confirmed the above (that Rotki enables preview on their `develop` branch).

**Pull request merged**
