### PR TITLE
Increase recursion limit in `ruff_linter`

### PR DESCRIPTION
**Pull request by zanieb**
See https://github.com/astral-sh/ruff/pull/10325#issuecomment-1992596557 for motivation. I'm not sure of the implications of the change.

### CODE REVIEW

**Comment by charliermarsh** [comment]
Huh?!?

**Comment by zanieb** [comment]
Something to do with the proc macros... this is beyond me. @snowsignal maybe you could take a look?

**Comment by MichaReiser** [comment]
The problem is that the `map_codes` macro creates a very long type signature in 

https://github.com/astral-sh/ruff/blob/e0bc08a7582d64f6e69a69835f748bff59922d6d/crates/ruff_macros/src/map_codes.rs#L390-L397

which is probably also very slow at runtime because we chain a very long sequence of iterators together, meaning that `next` need to check if any iterator still returns an element. 

I think we can rewrite the implementation to use a `Vec` instead. This has the downside that calling `iter` allocates but the method isn't called frequently (to my knowledge).  We potentially could do even better by unrolling `EnumIter` but that's a more involved change

**Comment by MichaReiser** [comment]
@zanieb I will close this PR because #10452 resolved the underlying issue without increasing the recursion limit.

**Pull request closed without merging**
