### PR TITLE
[`flake8-use-pathlib`] Recommend `Path.iterdir()` over `os.scandir()` (`PTH209`)

### PR DESCRIPTION
**Pull request by InSyncWithFoo**
## Summary

Per discussion at #14509.

## Test Plan

`cargo nextest run` and `cargo insta test`.

### CODE REVIEW

**Comment by AlexWaygood** [comment]
How does `Path.iterdir` compare in terms of performance? I realise that most of the `flake8-use-pathlib` rules risk suggesting changes that might make your code slower, but I believe this may be particularly bad. See the [docs for `Path.scandir`](https://docs.python.org/3.14/library/pathlib.html#pathlib.Path.scandir), which has been added in Python 3.14 (which is still in the alpha period):

> Using [scandir()](https://docs.python.org/3.14/library/pathlib.html#pathlib.Path.scandir) instead of [iterdir()](https://docs.python.org/3.14/library/pathlib.html#pathlib.Path.iterdir) can significantly increase the performance of code that also needs file type or file attribute information, because [os.DirEntry](https://docs.python.org/3.14/library/os.html#os.DirEntry) objects expose this information if the operating system provides it when scanning a directory.

It might at least be worth mentioning in the docs for this rule, if `Path.iterdir` is significantly slower.

**Comment by AlexWaygood** [comment]
@InSyncWithFoo it looks like you're comparing `Path.iterdir()` with `os.listdir()` there rather than `os.scandir()`. But yeah, I'd expect a comparison with `scandir()` to be similarly unfavourable. Please add a `## Known issues` to the docs for this rule saying that we expect this rule to result in slower code, and that you shouldn't enable it in performance-critical places.

If https://github.com/astral-sh/ruff/pull/14632 is accepted, we can also have this rule suggest `Path.scandir()` rather than `Path.iterdir()` if the user's target version is Python 3.14 or higher. That should address some of the performance concerns.

**Comment by MichaReiser** [comment]
I'm concerned about adding a rule that is a considerable foot gun for the majority of users when its only benefit is consistency. Especially because the use of `os.scandir` might be exactly because of its performance characteristics. 

I suggest we wait to add this rule until Python 3.14 is closer to stabilizing and only then suggest using `Path.scandir`.

**Comment by AlexWaygood** [comment]
@MichaReiser and I discussed this offline. There's a general issue with our `flake8-pathlib` rules that they could impact performance, but this case seems especially bad.

Our decision is that we'll keep `PTH208` (because `Path.iterdir()` is a drop-in replacement for `os.listdir()`), but we'll unfortunately reject this PR (because `Path.iterdir()` is not a drop-in replacement for `os.scandir()`, it does something _slightly_ different, and the likely reason they're using `os.scandir()` rather than `os.listdir()` is precisely because it's the option you want to use for maximum performance).

When Python 3.14 enters the beta period, we can consider adding a rule suggesting to replace `os.scandir` with `Path.scandir`, assuming the new API is still present when the beta period starts.

Sorry about this @InSyncWithFoo -- thanks for the PR anyway! Cc. @sbrugman also, since you were involved in the discussion in #14509

**Pull request closed without merging**
