### PR TITLE
[red-knot] consolidate diagnostic and inference tests

### PR DESCRIPTION
**Pull request by carljm**
Pull the tests from `types.rs` into `infer.rs`.

All of these are integration tests with the same basic form: create a code sample, run type inference or check on it, and make some assertions about types and/or diagnostics. These are the sort of tests we will want to move into a test framework with a low-boilerplate custom textual format. In the meantime, having them together (and more importantly, their helper utilities together) means that it's easy to keep tests for related language features together (iterable tests with other iterable tests, callable tests with other callable tests), without an artificial split based on tests which test diagnostics vs tests which test inference. And it allows a single test to more easily test both diagnostics and inference. (Ultimately in the test framework, they will likely all test diagnostics, just in some cases the diagnostics will come from `reveal_type()`.)

### CODE REVIEW

**Review by MichaReiser — APPROVED** [review]
I would be more leaning towards moving the tests in the other direction, considering that `types` is the API but whatever. Let's build a testing framework instead to solve this for good.

**Review by AlexWaygood — APPROVED** [review]

**Comment by carljm** [comment]
Yeah we could just as well put them in `types.rs`. It's not hard to do, I can push that change. But I agree, hopefully they don't stay in either of these files for too much longer.

**Comment by carljm** [comment]
Actually I'm not going to push that change because it will cause too much pain in rebasing my WIP on declared types, where I add a bunch of new tests :) We'll just leave them in `infer.rs` for now until they get moved into a testing framework.

**Comment by MichaReiser** [comment]
> Yeah we could just as well put them in `types.rs`. It's not hard to do, I can push that change. But I agree, hopefully they don't stay in either of these files for too much longer.

I'm fine either way. I prefer what ever takes the least of your time (which is what you have now)

**Pull request merged**
