### PR TITLE
FA102: add configuration to always require `annotations` future when annotations used

### PR DESCRIPTION
**Pull request by akx**
## Summary

This PR extends the FA102 lint with a configuration that makes it yell whenever type annotations are used in a file that doesn't have the import.

It's currently a bit loud since it complains about every annotation in a non-compliant file – and an autofix to add the import would be nice.

## Test Plan

* New test fixtures within.
* Tested against some production code (Found 7290 errors.)

### CODE REVIEW

**Comment by konstin** [comment]
Could you clarify with kinds of errors are you trying to catch with this setting? E.g.
```python
def main(arg: int) -> str:
    pass
```
should be valid in all supported python versions.

**Comment by akx** [comment]
> Could you clarify with kinds of errors are you trying to catch with this setting? E.g.

Well, e.g.
```python
class Foo:
   def copy(self) -> Foo:
       ...
```
would ordinarily require `-> "Foo"`.

**Comment by charliermarsh** [comment]
What's the motivation for this over setting [`required-imports`](https://beta.ruff.rs/docs/settings/#isort-required-imports)? Is it that you want to avoid `__future__` in some files?

**Comment by akx** [comment]
> What's the motivation for this over setting [`required-imports`](https://beta.ruff.rs/docs/settings/#isort-required-imports)? Is it that you want to avoid `__future__` in some files?

Yeah, pretty much that – I wouldn't want to litter files with an import that isn't required for no good reason (and the idea here is to introduce this to a project that already has quite some history).

I totally understand if this is too niche – feel free to close if you think it's out of scope :)

**Comment by charliermarsh** [comment]
Sorry for the delay here @akx. I think I'm gonna err on the side of "too niche" for now -- this is definitely reasonable, but I want to limit the number of ways to accomplish this, and I think `required-imports` is already a passable solution, since it doesn't add `__future__` to empty files, and should only really _affect_ files that make use of annotations anyway.

**Pull request closed without merging**
