### PR TITLE
Use `SmallVec` for binding references

### PR DESCRIPTION
**Pull request by charliermarsh**

### CODE REVIEW

**Comment by charliermarsh** [comment]
(Checking to see benchmarks.)

**Comment by MichaReiser** [comment]
Do we have any evidence that this improves performance? if not, then using a vec is fine.

**Comment by charliermarsh** [comment]
(Need to find a free moment to benchmark.)

**Review by MichaReiser — CHANGES_REQUESTED** [review]
To benchmark the change

**Comment by charliermarsh** [comment]
Closing until I have time to benchmark this.

**Pull request closed without merging**
