### PR TITLE
perf(formatter): Skip bodies without comments

### PR DESCRIPTION
**Pull request by MichaReiser**
## Summary

This PR improves the performance of the comments extraction by skipping over bodies that contain no comments. 

The visitor already avoided visiting the children of a node if there are no comments in its range but we aren't doing this yet for bodies because bodies are not nodes. 
This PR adds the logic for skipping over bodies if there's no comment in the body range. 

```python
if test: # a comment 
	... 
```

The old implementation did visit the `if` statement, as well as the `body` and `orelse` because it contains a comment in its range. But this is unnecessary
because only the case header has a comment. 

## Test Plan

`cargo test`

### CODE REVIEW

**Comment by MichaReiser** [comment]
Current dependencies on/for this PR:
* main
  * **PR #4954** <a href="https://app.graphite.dev/github/pr/astral-sh/ruff/4954" target="_blank">Graphite</a> 
    * **PR #4921** <a href="https://app.graphite.dev/github/pr/astral-sh/ruff/4921" target="_blank">Graphite</a> 
      * **PR #4922** <a href="https://app.graphite.dev/github/pr/astral-sh/ruff/4922" target="_blank">Graphite</a> 
        * **PR #4951** <a href="https://app.graphite.dev/github/pr/astral-sh/ruff/4951" target="_blank">Graphite</a> 
          * **PR #4961** <a href="https://app.graphite.dev/github/pr/astral-sh/ruff/4961" target="_blank">Graphite</a> 
            * **PR #4964** <a href="https://app.graphite.dev/github/pr/astral-sh/ruff/4964" target="_blank">Graphite</a> 
              * **PR #4978** <a href="https://app.graphite.dev/github/pr/astral-sh/ruff/4978" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/astral-sh/ruff/4978?utm_source=stack-comment).

**Comment by MichaReiser** [comment]
The benchmarks compare against `main` which does not yet have the `if statement` formatting. But we can see that the increase goes down from 25% slowdown to an at most 18% slowdown.

**Comment by konstin** [comment]
With https://github.com/astral-sh/ruff/pull/4964#issuecomment-1583012574, i don't really see much performance difference

**Review by konstin — APPROVED** [review]

**Comment by MichaReiser** [comment]
> With [#4964 (comment)](https://github.com/astral-sh/ruff/pull/4964#issuecomment-1583012574), i don't really see much performance difference

The linux result are in the range of what I expected and was able to reproduce locally. Not sure what happened with the windows run.

**Pull request merged**
