### PR TITLE
Consume the escaped Windows newline (`\r\n`) for `FStringMiddle`

### PR DESCRIPTION
**Pull request by dhruvmanila**
## Summary

This PR fixes a bug where if a Windows newline (`\r\n`) character was escaped, then only the `\r` was consumed and not `\n` leading to an unterminated string error.

## Test Plan

Add new test cases to check the newline escapes.

fixes: #7632

### CODE REVIEW

**Comment by dhruvmanila** [comment]
Current dependencies on/for this PR:
* main
  * **PR #7722** <a href="https://app.graphite.dev/github/pr/astral-sh/ruff/7722" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/astral-sh/ruff/7722?utm_source=stack-comment).

**Review by charliermarsh — APPROVED** [review]
Does this also account for the \r case (carriage return without newline character)?

**Comment by dhruvmanila** [comment]
> Does this also account for the \r case (carriage return without newline character)?

Yes, you can confirm that in the snapshots.

**Comment by qarmin** [comment]
Looks that this may also fix: (not reported yet, because I don't have file that cause problem)
```
...with the relevant file contents, the `pyproject.toml` settings, and the following stack trace, we'd be very appreciative!
panicked at 'The content 'integration_testing_environment.integration_testing_environment_ui. \
    menu.api_testka_menu.build_api_testka_menu' contains an unsupported '\r' line terminator character but text must only use line feeds '\n' as line separator. Use '\n' instead of '\r' and '\r\n' to insert a line break in strings.', crates/ruff_formatter/src/builders.rs:406:5
Backtrace:    0: ruff_cli::panic::catch_unwind::{{closure}}
             at ./ruff/crates/ruff_cli/src/panic.rs:31:25
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/alloc/src/boxed.rs:2007:9
   2: std::panicking::rust_panic_with_hook
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:709:13
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:597:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys_common/backtrace.rs:151:18
   5: rust_begin_unwind
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:593:5
   6: core::panicking::panic_fmt
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:67:14
   7: ruff_formatter::builders::debug_assert_no_newlines
             at ./ruff/crates/ruff_formatter/src/builders.rs:406:5
   8: <ruff_formatter::builders::SourceTextSliceBuilder as ruff_formatter::Format<Context>>::fmt
             at ./ruff/crates/ruff_formatter/src/builders.rs:392:9
   9: <ruff_python_formatter::other::identifier::FormatIdentifier as ruff_formatter::FormatRule<ruff_python_ast::nodes::Identifier,ruff_python_formatter::context::PyFormatContext>>::fmt
             at ./ruff/crates/ruff_python_formatter/src/other/identifier.rs:11:9
  10: <ruff_formatter::FormatRefWithRule<T,R,C> as ruff_formatter::Format<C>>::fmt
             at ./ruff/crates/ruff_formatter/src/lib.rs:608:9
  11: <core::option::Option<T> as ruff_formatter::Format<Context>>::fmt
             at ./ruff/crates/ruff_formatter/src/lib.rs:488:28
  12: ruff_formatter::arguments::Argument<Context>::new::formatter
             at ./ruff/crates/ruff_formatter/src/arguments.rs:43:13
  13: ruff_formatter::arguments::Argument<Context>::format
             at ./ruff/crates/ruff_formatter/src/arguments.rs:56:9
  14: <ruff_formatter::formatter::Formatter<Context> as ruff_formatter::buffer::Buffer>::write_fmt
             at ./ruff/crates/ruff_formatter/src/formatter.rs:220:22
  15: <ruff_python_formatter::statement::stmt_import_from::FormatStmtImportFrom as ruff_python_formatter::FormatNodeRule<ruff_python_ast::nodes::StmtImportFrom>>::fmt_fields
             at ./ruff/crates/ruff_python_formatter/src/statement/stmt_import_from.rs:27:9
  16: ruff_python_formatter::FormatNodeRule::fmt
             at ./ruff/crates/ruff_python_formatter/src/lib.rs:62:13
```

**Comment by dhruvmanila** [comment]
> Looks that this may also fix: (not reported yet, because I don't have file that cause problem)

I'm not sure. Maybe if we can get the file content, then we'll be able to diagnose correctly.

**Pull request merged**
