### PR TITLE
[`pylint`] Implement `redundant-unicode-prefix` (`W1406`)

### PR DESCRIPTION
**Pull request by diceroll123**
## Summary

Implements [`W1406`/`redundant-u-string-prefix`](https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/redundant-u-string-prefix.html)

See: #970 

## Test Plan

`cargo test`

### CODE REVIEW

**Comment by bluetech** [comment]
Ruff already implements [UP025](https://docs.astral.sh/ruff/rules/unicode-kind-prefix/), is there a difference or can they be aliases?

**Review by charliermarsh — APPROVED** [review]
Thanks!

**Comment by charliermarsh** [comment]
Ah sorry, I agree -- this should be identical to `UP025`, though I'm not seeing it in the playground (which is how I typically check for redundant rules: https://play.ruff.rs/3009f32d-71b3-4f1f-a320-2f6364c0051a). Need to investigate.

**Comment by charliermarsh** [comment]
Ah yeah, it is a duplicate -- sorry @diceroll123.

**Comment by diceroll123** [comment]
No worries!

**Pull request closed without merging**
