### PR TITLE
Use backticks for code in red-knot messages

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

...and remove periods from messages that don't span more than a single sentence.

This is more consistent with how we present user-facing messages in uv (which has a defined style guide).

### CODE REVIEW

**Comment by charliermarsh** [comment]
I might also suggest removing periods from the end of these error messages (unless they span more than one sentence). We use that policy in uv and in Ruff.

**Review by carljm — APPROVED** [review]
Thanks!

I have no problem with removing final periods, in this PR or another one; it makes sense to have a consistent style guide across projects.

**Comment by carljm** [comment]
Looks like there's one missed test to fix.

**Comment by charliermarsh** [comment]
Sounds good. I'll probably just bundle it here then to reduce churn (fewer commits to ignore when git blaming).

**Pull request merged**
