### PR TITLE
Stabilise rules RUF024 and RUF026

### PR DESCRIPTION
**Pull request by AlexWaygood**
## Summary

Stabilise the following rules in the `RUF` category for Ruff v0.5:

- `mutable-fromkeys-value`
- ~~`unnecessary-dict-comprehension`~~
- `default-factory-kwarg`
- ~~`parenthesize-chained-operators`~~
- ~~`unsorted-dunder-all`~~
- ~~`unsorted-dunder-slots`~~

These rules have been in the preview category for several minor releases, and were released to users >90 days ago. There are no open issues about any of them, and there have not been any open issues about any of them for several months. I skimmed over the implementations for all of them, and they all look reasonable to me (except for one test fixture for `RUF026` that wasn't testing what it was meant to be testing -- I fix that here as part of this PR).

## Test Plan

`cargo test`

### CODE REVIEW

**Comment by charliermarsh** [comment]
Generally looks reasonable (though we should review the ecosystem results when we can). `ParenthesizeChainedOperators` is the only one I'm unsure of because it's more opinionated but let's see what the ecosystem says.

**Comment by MichaReiser** [comment]
> `unsorted-dunder-all`, `unsorted-dunder-slots` 

could also be considered very-opinionated, but I'm not sure if this should prevent us from stabalizing.

**Comment by AlexWaygood** [comment]
For now, I've struck the following rules (all authored by me 😭) off the list:

- RUF021 (`parenthesize-chained-operators`)
- RUF022 (`unsorted-dunder-all`)
- RUF023 (`unsorted-dunder-slots`)

These rules are all working as designed, but they're all quite opinionated. Right now, it seems like promoting them to stable would be too disruptive for users who select the entire `RUF` category in their configuration file. Long-term, we'll need to figure out how to stabilise opinionated rules while minimising disruption for our users (which relates to our long-term ambition to rework our rule categorisation)

**Review by MichaReiser — APPROVED** [review]

**Comment by AlexWaygood** [comment]
> For now, I've struck the following rules (all authored by me 😭) off the list:

And I've now struck off RUF025 for similar reasons. Somewhat opinionated; has a fair few ecosystem hits; we can maybe consider it separately, but not for this PR...

**Pull request merged**
