### PR TITLE
Update fix safety FAQ to reflect `--unsafe-fixes`

### PR DESCRIPTION
**Pull request by charliermarsh**

### CODE REVIEW

**Review by zanieb — COMMENTED** [review]
This seems like too much detail for the FAQ (and it's clearly easy to miss), can you link to the configuration documentation instead?

**Comment by charliermarsh** [comment]
Ok, can do it in a little bit. (You're also welcome to do it and merge if you beat me to it.) We should include in 0.1.0.

**Comment by charliermarsh** [comment]
Picking it up now.

**Review by zanieb — APPROVED** [review]
Thanks!

**Pull request merged**
