### PR TITLE
[`ruff`] Stabilize unicode-to-unicode check for `ambiguous-unicode-xxx` (`RUF001`, `RUF002`, `RUF003`)

### PR DESCRIPTION
**Pull request by dylwil3**
This PR stabilizes the preview behavior introduced in #8473, where ambiguous unicode checks are flagged not only for unicode characters that may be confused for ASCII characters, but also for unicode characters that may be confused for other unicode characters.

Documentation has been updated to reflect this change.

Note: While there _are_ open issues related to these rules, none of them are affected by whether the behavior under review is in preview or not.

### CODE REVIEW

**Comment by dylwil3** [comment]
I'm not sure how I feel about these ecosystem changes (in stable - the preview changes seem to be messed up). Seems to me like the use of the "micro" mu vs the greek letter mu is pretty common and done accurately in the context of SI units (e.g. microseconds etc.) So I'm wondering if this behavior should not be stabilized. What do you think @AlexWaygood / @MichaReiser ?

**Comment by Skylion007** [comment]
> I'm not sure how I feel about these ecosystem changes (in stable - the preview changes seem to be messed up). Seems to me like the use of the "micro" mu vs the greek letter mu is pretty common and done accurately in the context of SI units (e.g. microseconds etc.) So I'm wondering if this behavior should not be stabilized. What do you think @AlexWaygood / @MichaReiser ?

Agreed, I feel like the micro use case would be way more common empirically than the greek letter.

**Comment by AlexWaygood** [comment]
Let's leave this for Ruff 0.8 and open an issue capturing these concerns 👍

**Comment by dylwil3** [comment]
Opened issue #14433 to track this

**Pull request closed without merging**
