### PR TITLE
Ruff 0.8

### PR DESCRIPTION
**Pull request by AlexWaygood**
## Summary

- https://github.com/astral-sh/ruff/pull/14382
- https://github.com/astral-sh/ruff/pull/14401
- https://github.com/astral-sh/ruff/pull/14406
- https://github.com/astral-sh/ruff/pull/13896
- https://github.com/astral-sh/ruff/pull/14405
- https://github.com/astral-sh/ruff/pull/13902
- https://github.com/astral-sh/ruff/pull/13473
- https://github.com/astral-sh/ruff/pull/14438
- https://github.com/astral-sh/ruff/pull/14435
- https://github.com/astral-sh/ruff/pull/14384
- https://github.com/astral-sh/ruff/pull/14385
- #14428
- https://github.com/astral-sh/ruff/pull/14450
- https://github.com/astral-sh/ruff/pull/14462
- #14457
- https://github.com/astral-sh/ruff/pull/14468
- https://github.com/astral-sh/ruff/pull/14480

## Test Plan

- `cargo test`
- Ecosystem report

### CODE REVIEW

**Comment by AlexWaygood** [comment]
The UP027 removal means that we now error on `setuptools`'s config, but only because they already explicitly `ignore` UP027, because it was deprecated: https://github.com/pypa/setuptools/blob/540001561bc2c6766940ba5fd6247735c1a3a290/ruff.toml#L40. I think that's fine.

**Comment by Skylion007** [comment]
Since we are stabilizing things, there seem to be many lower risk FURB rules we could stabilize: https://docs.astral.sh/ruff/rules/#refurb-furb

**Comment by AlexWaygood** [comment]
Thanks @Skylion007. I'll be spending a bunch of time this week looking through which rules are suitable for stabilisation in this release. I'll make sure to look at those, among many others :-)

**Comment by Avasam** [comment]
> The UP027 removal means that we now error on `setuptools`'s config, but only because they already explicitly `ignore` UP027, because it was deprecated: [pypa/setuptools@`5400015`/ruff.toml#L40](https://github.com/pypa/setuptools/blob/540001561bc2c6766940ba5fd6247735c1a3a290/ruff.toml#L40). I think that's fine.

Btw I got a relevant feature request to make those warnings by default: https://github.com/astral-sh/ruff/issues/13505

**Comment by MichaReiser** [comment]
Hmm, the branch is now failing

**Comment by AlexWaygood** [comment]
I saw (but don't yet understand why). Would you be able to take a look?

**Comment by MichaReiser** [comment]
Looking, but I can't repro locally :confused:

**Review by MichaReiser — APPROVED** [review]

**Comment by Skylion007** [comment]
Ah, the FURB rules didn't make it? ;-;

**Comment by AlexWaygood** [comment]
> Ah, the FURB rules didn't make it? ;-;

Not this release, unfortunately. I did look at them, but I'm a little concerned that these rules are quite highly opinionated. I'm not sure all users would agree that the changes they recommend would result in more idiomatic Python; I think they're very subjective.

The long-term answer to this problem is to improve our rule categorisation so that we can clearly signal to users that these are highly opinionated rules and have them disabled by default. Unfortunately I can't tell you when rule recategorisation is likely to happen, however :-(

**Comment by Skylion007** [comment]
@AlexWaygood I agree with most of the FURB rules but, FURB131, FURB132, and FURB145 have performance implications in code which is why I wanted to enable those specifically. FURB148 also just removes an unused variable, but I can see why that might want to be left in preview because the fixit is more complicated.

**Comment by AlexWaygood** [comment]
It's possible that some of these might make a tiny difference to performance, but I think it's very unlikely to make a significant difference unless you're in a very hot loop. The recommendations to avoid slicing are also the kind of thing where relative performance of different idioms is likely to change quite a lot between Python releases (especially right now, when there's a lot of work going into Python performance, and when [very significant optimisations for slices](https://github.com/python/cpython/pull/125064) have just been landed on the CPython `main` branch).

**Pull request merged**
