### PR TITLE
Add support for PEP 701

### PR DESCRIPTION
**Pull request by dhruvmanila**
## Summary

This PR adds support for PEP 701 in Ruff. This is a rollup PR of all the other individual PRs. The separate PRs were created for logic separation and code reviews. Refer to each pull request for a detail description on the change.

#### Parser

- #6659 
- #7041 
- #7211 
- #7263 
- #7331
- #7378 
- #7667

#### Linter

- #7325 
- #7326 
- #7327 
- #7328 
- #7329
- #7387
- #7477 
- #7515 
- #7588 
- #7589
- #7690

#### Formatter

- #7586 
- #7597 

### Formatter ecosystem checks

Explanation for the change in ecosystem check: https://github.com/astral-sh/ruff/pull/7597#issue-1908878183

#### `main`

```
| project      | similarity index  | total files       | changed files     |
|--------------|------------------:|------------------:|------------------:|
| cpython      |           0.76083 |              1789 |              1631 |
| django       |           0.99983 |              2760 |                36 |
| transformers |           0.99963 |              2587 |               319 |
| twine        |           1.00000 |                33 |                 0 |
| typeshed     |           0.99983 |              3496 |                18 |
| warehouse    |           0.99967 |               648 |                15 |
| zulip        |           0.99972 |              1437 |                21 |
```

#### `dhruv/pep-701`

```
| project      | similarity index  | total files       | changed files     |
|--------------|------------------:|------------------:|------------------:|
| cpython      |           0.76051 |              1789 |              1632 |
| django       |           0.99983 |              2760 |                36 |
| transformers |           0.99963 |              2587 |               319 |
| twine        |           1.00000 |                33 |                 0 |
| typeshed     |           0.99983 |              3496 |                18 |
| warehouse    |           0.99967 |               648 |                15 |
| zulip        |           0.99972 |              1437 |                21 |
```

### CODE REVIEW

**Comment by dhruvmanila** [comment]
Current dependencies on/for this PR:
* main
  * **PR #7376** <a href="https://app.graphite.dev/github/pr/astral-sh/ruff/7376" target="_blank">Graphite</a>  👈
    * **PR #7325** <a href="https://app.graphite.dev/github/pr/astral-sh/ruff/7325" target="_blank">Graphite</a> 
      * **PR #7326** <a href="https://app.graphite.dev/github/pr/astral-sh/ruff/7326" target="_blank">Graphite</a> 
        * **PR #7327** <a href="https://app.graphite.dev/github/pr/astral-sh/ruff/7327" target="_blank">Graphite</a> 
          * **PR #7328** <a href="https://app.graphite.dev/github/pr/astral-sh/ruff/7328" target="_blank">Graphite</a> 
            * **PR #7329** <a href="https://app.graphite.dev/github/pr/astral-sh/ruff/7329" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/astral-sh/ruff/7376?utm_source=stack-comment).

**Comment by MichaReiser** [comment]
Would you mind running ` ./scripts/formatter_ecosystem_checks.sh` before merging and ensuring the numbers are identical to `main`?

**Comment by dhruvmanila** [comment]
Ugh, I messed up a rebase and removed the logical line rules PR commit 😓 

I've manually merged the branch locally and pushed it but the details can be found in the original PR: #7690

**Comment by dhruvmanila** [comment]
The ecosystem checks for the linter looks good as we now detect violations inside f-strings as well. We'll avoid the ones for which it's hard to distinguish between usages like `:` for format spec vs dictionary.

The formatter ecosystem checks are unchanged except for one file which we're able to parse now (`test_fstring.py` in CPython repository) as it contained PEP 701 syntax.

**Comment by hugovk** [comment]
Thank you for all your work on this!

**Comment by konstin** [comment]
:tada:

**Comment by MichaReiser** [comment]
Congrats on landing this huge change 🎸 🎸 🎸

**Comment by dhruvmanila** [comment]
Thank you all for your comments! 😄

**Pull request merged**
