### PR TITLE
Add Applicability to pyupgrade

### PR DESCRIPTION
**Pull request by evanrittenhouse**
## Summary

Fixes some of #4184. The `manual` fixes here are because they involve deprecations and I'm hesitant to classify version-based fixes as automatic/suggested if they cause a regression in the user's code.

### CODE REVIEW

**Comment by charliermarsh** [comment]
I'd vote to make all of the "manual" fixes here "suggested". Users will need to opt-in to fixing them anyway. I think we should reserve "manual" for cases in which the fix is likely to be incorrect as-is.

**Comment by evanrittenhouse** [comment]
My only worry there is that the user may not know that it's version-gated. I believe we have a way to check the Python version a user is running and emit diagnostics that way - should I add those checks to the rules in question here and change to suggested? @charliermarsh

**Comment by charliermarsh** [comment]
I believe all of those rules are properly gated already though (or they apply to all versions >= Python 3.7).

**Comment by evanrittenhouse** [comment]
Ahhh gotcha, I didn't see any gates so I wanted to be safe. I'll change these back. 

Out of curiosity, where does that gating occur?

**Comment by charliermarsh** [comment]
It depends on the rule. Some of these are applicable to all supported versions (>= 3.7), so we don't need to gate at all. Other pyupgrade rules are gated in `checkers/ast/mod.rs` (so they're just not invoked on unsupported versions). The deprecated import rule takes the `version` as a field on `ImportReplacer` and bases the checks on that.

**Comment by evanrittenhouse** [comment]
Done - thanks for the suggestion @charliermarsh !

**Comment by charliermarsh** [comment]
(Looks like there's a small merge conflict.)

**Pull request merged**
