### PR TITLE
[refurb] Implement `read-whole-file` [`FURB101`]

### PR DESCRIPTION
**Pull request by SavchenkoValeriy**
## Summary

This PR is part of a bigger effort of re-implementing `refurb` rules #1348. It adds support for [FURB101](https://github.com/dosisod/refurb/blob/master/refurb/checks/pathlib/read_text.py)

## Test Plan

I included a new test + checked that all other tests pass.

### CODE REVIEW

**Comment by SavchenkoValeriy** [comment]
Hey @charliermarsh 👋 Do you mind taking a look at this PR? Thanks! 🙏 
PS I think that the performance test failure is a flake

**Comment by charliermarsh** [comment]
Sorry, this is absolutely on my list, it's just a big rule implementation so trying to find time to focus on it.

**Comment by SavchenkoValeriy** [comment]
@charliermarsh a gentle ping

**Review by charliermarsh — APPROVED** [review]

**Comment by SavchenkoValeriy** [comment]
Oh, really nice catch with argument unpacking! ❤️

**Comment by charliermarsh** [comment]
@SavchenkoValeriy - I think there are a few cases we _could_ catch, but it felt like it didn't merit the complexity budget.

**Comment by charliermarsh** [comment]
Excellent work @SavchenkoValeriy

**Pull request merged**
