### PR TITLE
CI: Treat mdtest Markdown files as code

### PR DESCRIPTION
**Pull request by sharkdp**
## Summary

Make sure we run the tests for mdtest-only changes.

## Test Plan

Tested if positive glob patterns override negative patterns here: https://codepen.io/mrmlnc/pen/OXQjMe

Will test using the changes in https://github.com/astral-sh/ruff/pull/14652 (where tests were previously skipped)

### CODE REVIEW

**Review by AlexWaygood — APPROVED** [review]
LGTM if it works. Is it worth pushing a temporary commit to an md file here to make sure it triggers CI, and then reverting it again afterwards?

**Comment by AlexWaygood** [comment]
Oh I guess CI will always be triggered here anyway, because this PR edits the workflow file. So the temporary commit would also have to remove the line in this workflow file that means that CI is triggered if the workflow file itself is edited in a PR

**Comment by AlexWaygood** [comment]
Sounds good!

**Comment by sharkdp** [comment]
Seems to work as intended.

**Pull request merged**
