### PR TITLE
[red-knot] Add filename and source location for diagnostics

### PR DESCRIPTION
**Pull request by dhruvmanila**
## Summary

I'm not sure if this is useful but this is a hacky implementation to add the filename and row / column numbers to the current Red Knot diagnostics.

cc @carljm, thoughts?

### CODE REVIEW

**Comment by dhruvmanila** [comment]
I can update the test if this format is good enough. It's a bit difficult to include the range for `lint_override` because we'd need to find out the actual `@override` decorator node.

**Review by MichaReiser — APPROVED** [review]

**Comment by MichaReiser** [comment]
I think this is fine. But I would probably not spend too much time on `lint_override` because we may want to remove the lint rule anyway.

**Review by carljm — APPROVED** [review]
100% agree with Micha: this looks good and useful and worth fixing up the tests and landing, but I wouldn't spend extra time on `lint_override`.

**Comment by AlexWaygood** [comment]
It looks like some of these tests might be failing on Windows on `main` due to windows paths having different display representations: https://github.com/astral-sh/ruff/actions/runs/10355375507/job/28662886847?pr=12748

**Pull request merged**
