### PR TITLE
Accept commas in default copyright pattern

### LINKED ISSUE #9477: Default copyright pattern doesn't allow commas
As of ruff 0.1.11, the default `notice-rgx` does not allow for headers that have commas, like:

> Copyright (c) 2018, 2019 Developers

[Part of the docs](https://github.com/astral-sh/ruff/blob/eb4ed2471b48d6ccba74064c65e37e32cba41a6c/crates/ruff_workspace/src/options.rs#L1065-L1076) do say that `(?i)Copyright\s+(\(C\)\s+)?\d{4}([-,]\d{4})*` is the default pattern (which works), but there's also `(?i)Copyright\s+(\(C\)\s+)?\d{4}(-\d{4})*` mentioned in a separate sentence in the docs and matches what's in [`COPYRIGHT`](https://github.com/astral-sh/ruff/blob/eb4ed2471b48d6ccba74064c65e37e32cba41a6c/crates/ruff_linter/src/rules/flake8_copyright/settings.rs#L16C29-L16C73) (and reflects actual behavior). Any reason commas shouldn't be accepted?

### PR DESCRIPTION
**Pull request by dopplershift**
## Summary

Adds commas as an accepted separator between copyright years by default, which is actually documented in one spot, but not currently accurate. Fixes #9477.

### CODE REVIEW

**Comment by charliermarsh** [comment]
Just trying to add tests for this... It seems like `Copyright (c) 2018, 2019 Developers` is actually accepted on main? See: https://play.ruff.rs/5c5932af-5fef-4990-bcc5-c854c0b46255

**Comment by charliermarsh** [comment]
It seems like the current regex could be described as "Must contain `Copyright\s+(\(C\)\s+)?\d{4}`, followed by anything". So `Copyright (c) 2018, 2019 Developers` would match as "`Copyright (c) 2018`, followed by anything".

**Comment by BurntSushi** [comment]
> It seems like the current regex could be described as "Must contain `Copyright\s+(\(C\)\s+)?\d{4}`, followed by anything". So `Copyright (c) 2018, 2019 Developers` would match as "`Copyright (c) 2018`, followed by anything".

Nit: you probably want `[0-9]` instead of `\d`. Or, equivalently, `(?-u:\d)`. See: https://docs.rs/regex/latest/regex/#example-validating-a-particular-date-format

**Comment by charliermarsh** [comment]
Closing for now, but happy to revisit if we get more info.

**Review by charliermarsh — APPROVED** [review]

**Pull request merged**
