### PR TITLE
[`flake8-bandit`] Implement upstream updates for `S311`, `S324` and `S605`

### PR DESCRIPTION
**Pull request by mkniewallner**
## Summary

Pick up updates made in latest [releases](https://github.com/PyCQA/bandit/releases) of `bandit`:
- `S311`: https://github.com/PyCQA/bandit/pull/940 and https://github.com/PyCQA/bandit/pull/1096
- `S324`: https://github.com/PyCQA/bandit/pull/1018
- `S605`: https://github.com/PyCQA/bandit/pull/1116

## Test Plan

Snapshot tests

### CODE REVIEW

**Comment by mkniewallner** [comment]
Not sure why there is a new match for `S607` in the ecosystem check as it was not changed.

**Review by charliermarsh — APPROVED** [review]
Nice, this looks great -- thanks!

**Comment by charliermarsh** [comment]
> Not sure why there is a new match for S607 on zulip in the ecosystem check as it was not changed.

I think it's because you added `getstatusoutput` to the list of shell-like calls.

**Comment by mkniewallner** [comment]
> > Not sure why there is a new match for S607 on zulip in the ecosystem check as it was not changed.
> 
> I think it's because you added `getstatusoutput` to the list of shell-like calls.

Oh yeah sorry, I did not know what S607 was exactly, and didn't see that this change would also apply to this rule. But it does seem legit to handle this new case for S607, as this is the core logic to detect shell invocations, so all good it seems!

**Pull request merged**
