### PR TITLE
[`pydocstyle-D405`] Allow using `parameters` as a sub-section header

### PR DESCRIPTION
**Pull request by mikeleppane**
## Summary

This review contains a fix for [D405](https://docs.astral.sh/ruff/rules/capitalize-section-name/) (capitalize-section-name)
The problem is that Ruff considers the sub-section header as a normal section if it has the same name as some section name. For instance, a function/method has an argument named "parameters".  This only applies if you use Numpy style docstring.

See: [ISSUE](https://github.com/astral-sh/ruff/issues/9806)

The following will not raise D405 after the fix:
```python  
def some_function(parameters: list[str]):
    """A function with a parameters parameter

    Parameters
    ----------

    parameters:
        A list of string parameters
    """
    ...
```

## Test Plan

```bash
cargo test
```

### CODE REVIEW

**Comment by mikeleppane** [comment]
Note: check that the condition still holds if an arg name is different than Parameters but some other section name e.g returns.

**Comment by charliermarsh** [comment]
@mikeleppane - Can you post an example?

**Comment by mikeleppane** [comment]
Sorry, I forgot to add a test case for this.

```python

def foo(returns: int):
   """
   Parameters
   -‐-----------------
   returns:
       some value

   """

**Comment by charliermarsh** [comment]
Ahh ok yes, the change I made here doesn't cover that case.

**Comment by charliermarsh** [comment]
I have an idea for it, thanks.

**Comment by charliermarsh** [comment]
Thanks as always @mikeleppane!

**Pull request merged**
