### PR TITLE
Pre-compute the module range for LALRPOP parser

### PR DESCRIPTION
**Pull request by dhruvmanila**
## Summary

This PR updates the LALRPOP to use the complete source range for module by looking at the tokens before the parsing begins. This means the module range now corresponds to the actual source even if it only contains trivia tokens. This is mainly so that the fuzzer doesn't crash because the AST doesn't match.

### CODE REVIEW

**Review by MichaReiser — APPROVED** [review]

**Comment by MichaReiser** [comment]
Oh no, the formatter fails now. I think we need to fix

https://github.com/astral-sh/ruff/blob/e2ec42539bfedc13270a2164faebe61e3c2e51dd/crates/ruff_python_formatter/src/module/mod_module.rs#L19-L23

to count the lines between range instead of after.

**Comment by MichaReiser** [comment]
I went ahead and pushed the fix. I hope that's okay with you

**Comment by dhruvmanila** [comment]
Thank you!

**Comment by dhruvmanila** [comment]
Ugh, I force pushed the branch and removed your change, I'll fix this.

**Pull request merged**
