### PR TITLE
format StmtBreak

### PR DESCRIPTION
**Pull request by davidszotten**
## Summary

format `StmtBreak`

trying to learn how to help out with the formatter. starting simple

## Test Plan

new snapshot test

### CODE REVIEW

**Review by konstin — APPROVED** [review]
thanks

**Comment by davidszotten** [comment]
do i need any custom comment handling like in https://github.com/astral-sh/ruff/blob/30574e1a196912baaa94620fc217f53b647c41b5/crates/ruff_python_formatter/src/statement/stmt_while.rs#L21  ? if not, how come it's needed for `while`?

**Comment by konstin** [comment]
`FormatNodeRule` has default implementations for `fmt_leading_comments`, `fmt_trailing_comments` and `fmt_dangling_comments` which do the right thing for `break` (a comment can be on its own line before the `break` or trailing the `break` either on the same line or on its own line line after).

For `while` it's more complicated, e.g. you can have

```python
while x: # trailing condition comment, do not indent
    body # trailing body comment, keep with body
    # trailing body comment, keep with body
# leading else comment, keep with else
else:  # trailing else comment, do not indent either
    print("else")
```

Since our AST is often lacking nodes for parts of the syntax, we often have to set comments as "dangling" in placements.rs and handle them manually in the node formatting. For the `while` case there is e.g. no node for the `else`, we get the or body as a `Vec<Stmt>`. That means we get comments once for the entire while-else statement and have to parse out the leading else comments. Similarly the `:` doesn't have any representation, so we mark trailing comments after a colon [here](https://github.com/astral-sh/ruff/blob/66089e1a2e4b8b6ad6de3dc9543cd9a8d2a764e3/crates/ruff_python_formatter/src/comments/placement.rs#L576).

**Comment by davidszotten** [comment]
thank you, i sort of followed that. will hopefully become more clear as i dig in more

**Comment by charliermarsh** [comment]
Thanks @davidszotten!

**Pull request merged**
