### PR TITLE
Detect runtime-evaluated base classes defined in the current file

### LINKED ISSUE #8250: Reference to `runtime-evaluated-base-classes` in the same file don't work
For some reason, `semantic.resolve_call_path(map_subscript(base))` resolves to `None` when the reference is in the same file.

https://github.com/astral-sh/ruff/blob/f5e850745cc9bcaeb308a3a139b4e86db58096aa/crates/ruff_linter/src/rules/flake8_type_checking/helpers.rs#L43-L44

* A minimal code snippet that reproduces the bug.

In this example, `example1.MyBaseClass` is a runtime evaluated base class.

### example1.py

This triggers `TCH003` for `Sequence`.

```python
from __future__ import annotations

from collections.abc import Sequence  # TCH003


class MyBaseClass:
    pass


class Foo(MyBaseClass):
    foo: Sequence
```

### example2.py

This is `TCH` compliant.

```python
from __future__ import annotations

from collections.abc import Sequence

from example1 import MyBaseClass


class Foo(MyBaseClass):
    foo: Sequence
```

* The command you invoked (e.g., `ruff /path/to/file.py --fix`), ideally including the `--isolated` flag.

`ruff --select TCH example1.py example2.py`

* The current Ruff settings (any relevant sections from your `pyproject.toml`).

```
[tool.ruff.flake8-type-checking]
runtime-evaluated-base-classes = [
  "example1.MyBaseClass",
]
```

* The current Ruff version (`ruff --version`).

Main branch, currently 0.1.1.

### PR DESCRIPTION
**Pull request by evanrittenhouse**
## Summary
Detect runtime-evaluated base classes defined in the file we're currently linting. Closes #8250

### CODE REVIEW

**Comment by evanrittenhouse** [comment]
Going to fix the Clippy error in the morning

**Comment by charliermarsh** [comment]
@evanrittenhouse - Do you mind giving me commit privileges on this branch?

**Comment by charliermarsh** [comment]
I re-opened here with you as co-author: https://github.com/astral-sh/ruff/pull/8572

**Comment by evanrittenhouse** [comment]
Sounds good. Should've added some tests, totally spaced.

**Pull request closed without merging**
