### PR TITLE
[red-knot] feat: implement all rich comparison operators

### PR DESCRIPTION
**Pull request by Slyces**
The algorithm for rich comparison still has some todo items

## Summary

The algorithm to perform rich comparisons on instances is non trivial. #13571 introduced a placeholder for `__lt__`.

This PR addresses some of the `// TODO` and contributes towards #13618.

## Test Plan

To be done, this is why the PR is still a draft

### CODE REVIEW

**Comment by carljm** [comment]
We may want to get this in place soon; let us know if you'd like to continue with it, or if it would be better for one of us to pick it up and get it ready to land!

**Comment by Slyces** [comment]
Hi, I've been a bit busy with work recently, I don't mind if someone picks the ticket!

**Comment by carljm** [comment]
No problem, thanks for replying! (And for all your contributions over the last few weeks.)

No need to close this PR, it may be useful reference / starting point. But (until/unless we hear otherwise) we'll assume that you aren't working on it and it's safe for one of us to pick it up from here, without duplicating work.

**Comment by cake-monotone** [comment]
If it’s alright with you, would it be okay for me to continue with this work?

**Comment by carljm** [comment]
> If it’s alright with you, would it be okay for me to continue with this work?

I think @Slyces already clarified above that this is open for someone else to pick up, so feel free to go ahead. And thank you!!

**Comment by AlexWaygood** [comment]
Implemented by @cake-monotone in https://github.com/astral-sh/ruff/pull/13903. Thanks so much for your work here, really appreciate it!!

**Pull request closed without merging**
