### PR TITLE
[`ruff`] Do not report when `Optional` has no type arguments (`RUF013`)

### LINKED ISSUE #13833: RUF013 incorrectly emitted on invalid annotation with bare `Optional`
Here is the bad code diff
```diff
-        hsdp_device_mesh: Optional = None,
+        hsdp_device_mesh: Optional[Optional] = None,
```
Obviously, an untyped Optional is fine, and `Optional[Optional]` doesn't make much sense here as an autofix. 
* version ruff 0.7.0
* ruff check RUF013 --select=RUF013 . --fix --unsafe-fixes

### PR DESCRIPTION
**Pull request by InSyncWithFoo**
## Summary

Resolves #13833.

## Test Plan

`cargo nextest run` and `cargo insta test`.

### CODE REVIEW

**Review by MichaReiser — CHANGES_REQUESTED** [review]
Thanks. 

I think we should add this check to `type_hint_explicitly_allows_none` so that `Annotated[Optional, "bla"]` also works

**Review by charliermarsh — APPROVED** [review]

**Comment by henryiii** [comment]
I'm confused, bare `Optional` still isn't a valid type annotation for type checkers. `Optional` would be `Optional[Any]`, which expands to `Union[None, Any]`, but a `Union` with `Any` is just `Any`. I thought the problem was the suggested fix, `Optional[Optional]` was nonsense.

**Comment by charliermarsh** [comment]
That’s correct but seems outside the scope of the rule? Like a bare Optional being invalid should be its own rule.

**Comment by henryiii** [comment]
Ah, yes, that makes sense.

**Pull request merged**
