### PR TITLE
Use `.yml` suffix consistently

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

We use `.yaml` for ~half of our YAML files, and `.yml` for the other half. This PR standardizes on `.yml`. I don't have a strong preference between the two, but `cargo-dist` prefers `.yml`, so seems easier to fall on that side of the argument.

### CODE REVIEW

**Comment by MichaReiser** [comment]
Pre commit doesn't agree 🤣

**Comment by charliermarsh** [comment]
Heavy sigh

**Comment by bswck** [comment]
😭

**Comment by zanieb** [comment]
fwiw I have the smallest of preferences for `yaml`.

**Comment by charliermarsh** [comment]
Yeah me too. I'm probably going to change it anyway though, since cargo-dist requires it and it's not a strong enough preference for me to change my mind on a bigger tooling decision based on the suffix alone.

**Comment by MichaReiser** [comment]
> Yeah me too. I'm probably going to change it anyway though, since cargo-dist requires it and it's not a strong enough preference for me to change my mind on a bigger tooling decision based on the suffix alone.

For which files does `cargo-dist` require `.yml`? Could we only change these files (yml is impossible to pronounce)

**Comment by charliermarsh** [comment]
`release.yml` (which is auto-generated), and then the files that are automatically referenced as sub-steps (e.g., `publish-to-pypi.yml`).

**Comment by charliermarsh** [comment]
I'll just close this then and bundle it with the `cargo-dist` PR. I figured it'd be easier to stage it separately, but seems not.

**Pull request closed without merging**
