### PR TITLE
[`flake8-async`] Update `ASYNC100` to match upstream

### PR DESCRIPTION
**Pull request by augustelalande**
## Summary

Update the name of `ASYNC100` to match [upstream](https://flake8-async.readthedocs.io/en/latest/rules.html).

Also update to the functionality to match upstream by supporting additional context managers from asyncio and anyio. Matching this [list](https://flake8-async.readthedocs.io/en/latest/glossary.html#timeout-context).

Part of #12039.

## Test Plan

Added the new context managers to the fixture.

### CODE REVIEW

**Review by MichaReiser — APPROVED** [review]
Awesome, thank you!

I think we should gate this change behind preview because it changes the scope of the rule.

**Comment by augustelalande** [comment]
Not super straight forward to gate since it's just detecting a few additional context managers. I think there's precedence for not gating when just detecting more functions, e.g., #12065

**Comment by MichaReiser** [comment]
The way this differs in my view from the numpy rule is that the NumPy rule was made more complete by including more of the deprecated methods. This PR introduces support for entire new async libraries, which extends the scope of the rule. @zanieb what's your take on this?

**Comment by augustelalande** [comment]
Ok no problem. I did the gating.

**Review by charliermarsh — APPROVED** [review]
Thank you!

**Pull request merged**
