### PR TITLE
Make RET504 also work with StmtAugAssign and StmtAnnAssign AST nodes

### LINKED ISSUE #9327: Request: extending `unnecessary-assign` (`RET504`) to account for `+=` (`__iadd__`)
With `ruff==0.1.9`'s [`unnecessary-assign`](https://docs.astral.sh/ruff/rules/unnecessary-assign/) (`RET504`), this goes undetected as having extra steps:

```python
def foo(arg: int) -> int:
    arg += 1
    return arg
```

It would be cool to extend this rule to request:

```python
def foo(arg: int) -> int:
    return arg + 1
```

There is a side effect here, it moves from invoking `__iadd__` to `__add__`. So perhaps an autofix for this should be considered an "unsafe" fix

### PR DESCRIPTION
**Pull request by evanrittenhouse**
## Summary

Closes #9327 

## Test Plan

Unit tests

### CODE REVIEW

**Comment by Skylion007** [comment]
This feels like it should be controlled by a rule level setting as this return statement has slightly different semantics if it's a list / mutable type. Perhaps the additional constraint that this only be applied if the object is an immutable type should be applied?

```python
a = [1]
def f(c):
    c += [2]
    return c

assert a is f(a)

c = [1]

def g(c):
    return c + [2]

assert c is g(c)
```
the top assertion will pass while the 2nd assertion will fail.

**Comment by evanrittenhouse** [comment]
> Perhaps the additional constraint that this only be applied if the object is an immutable type should be applied?

AFAIK Ruff doesn't know how to check static types (maybe something's changed since I was last around). I'm happy to remove the `Name` clause in the match statement and leave it as only making the change if we see a `NumberLiteral` though

**Comment by Skylion007** [comment]
@evanrittenhouse I am pretty sure RUFF has very limited static type checking (basically only if the variable is initialized inside of the function). We could use that to only flag ints, floats, and other builtin immutable types.

**Comment by evanrittenhouse** [comment]
We may just want to leave it as `NumberLiteral`s/string literals only, actually - we seemingly can't tell, based on the AST only, if a `ExprName` refers to something immutable or not. There's the `is_mutable_expr` helper function which we can use to check, but again, `ExprName` would be considered "immutable" there, and something like:
```python
b = []
a = [1]
b += a
return b
```
would succeed and still be "unsafe".

So the best way forward may just be to only call this on strings/numbers. Thoughts @zanieb ?

**Comment by jamesbraza** [comment]
Cc @zanieb @charliermarsh wdyt of adding this as a 0.2.0 milestone? It seems to be pretty close

**Comment by zanieb** [comment]
Sorry about the delay here! I've somehow gotten to the point where GitHub mentions get buried :'( 

I think the first thing to do is to gate the behavior with preview mode — then we can stabilize the behavior later once we're confident it's correct.

We can also consider the fix safe or unsafe depending on our ability to determine the type? I think applying this fix to the following makes sense for:

- A binding that is local to the function with any type 
- An external binding with a known immutable type

For example, in the ecosystem checks we have [this violation](https://github.com/zulip/zulip/blob/9f009a2e638220ad4aaa791407e28d4f8dad9922/tools/lib/provision_inner.py#L75-L78) where a mutable local variable has an augmented assignment. I guess looking at that code, I'm wondering if this change would actually be more readable? I clicked on [another random violation](https://github.com/apache/airflow/blob/9f90a655e884be0a99ee80564c41190260fa9ba1/airflow/providers/google/cloud/operators/mlengine.py#L69-L78) and don't see what value it would provide to collapse onto the `return` statement.

What do you think? @charliermarsh might have more concrete advice

**Comment by MichaReiser** [comment]
I'll close this PR because it has gone stale. Feel free to reopen it if you're interested in moving the PR forward.

**Pull request closed without merging**
