### PR TITLE
Deprecate `PGH001` in favor of `S307`

### LINKED ISSUE #7283: Apparent duplicate rule (`S307` and `PGH001`)
Rules [`suspicious-eval-usage` (`S307`)](https://beta.ruff.rs/docs/rules/suspicious-eval-usage/) and [`eval` (`PGH001`)](https://beta.ruff.rs/docs/rules/eval/) seem to do the same thing. If they are, in fact, distinct, then the difference between them should probably be explained in the documentation.

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

These rules are identical. Bandit is the more popular and more well-defined category, so we remove `PGH001` and add a redirect to `S307`. (By adding the redirect, we ensure that users see a warning but not an error when they reference `PGH001` in their configuration or in a `# noqa`, and that those codes seamlessly redirect to `S307`.)

Closes https://github.com/astral-sh/ruff/issues/7283.

### CODE REVIEW

**Review by dhruvmanila — APPROVED** [review]

**Comment by MichaReiser** [comment]
Is this a breaking change? What do we need to document in the changelog?

**Review by konstin — APPROVED** [review]

**Comment by charliermarsh** [comment]
Yes and no...

If users have `PGH001` explicitly selected or ignored in their configuration file, we'll show a warning but automatically redirect it to `S307`.

If users have `# noqa: PGH001`, we'll similarly warn-and-redirect to `S307`.

The main _problem_ here is that if users have `PGH` in their `select`, but _not_ `S`, this rule will no longer run on their code. That's kind of an issue, because the rule is basically being silently turned off (and is the source of the ecosystem changes).

I'm not sure how best to resolve -- any ideas?

**Comment by charliermarsh** [comment]
@zanieb - This one actually might be interesting to you too (especially my comment about regarding redirects).

**Comment by Skylion007** [comment]
We really should implement proper rule aliasing, this getting more and more unwieldy as we add new rules. It's really surprising when a new user migrates a flake8-plugin to ruff only to find they also have to enable a bunch of rules in different other categories to make functionality of the original plugin.

**Comment by zanieb** [comment]
> The main problem here is that if users have PGH in their select, but not S, this rule will no longer run on their code. That's kind of an issue, because the rule is basically being silently turned off

This sounds like a breaking change to me. Proper aliasing does sound like the better solution and probably something we need for recategorization anyway?

**Comment by Skylion007** [comment]
@zanieb Agree, public rule aliasing is probably one of the largest painpoints right now and it will only become a bigger maintenance burden on us later the more rules get added without this feature.

**Comment by charliermarsh** [comment]
Separate from the larger conversation around rule aliasing (see my comment in the related issue), we should consider removing this whole category and marking it as a breaking change. There are so few rules, multiple of them are duplicates of other existing rules, and there's no semantic relationship _between_ the various rules.

**Comment by charliermarsh** [comment]
> Proper aliasing does sound like the better solution and probably something we need for recategorization anyway?

I think there are ways for us to do a recategorization without aliasing, because it doesn't require that we support _multiple_ codes at once for a given rule, only that we provide tooling to remap from existing to updated codes and categories.

**Comment by zanieb** [comment]
Should we remove the whole category instead of this pull request? Either way I think we should probably gate removal with preview.

**Comment by charliermarsh** [comment]
I’m in favor of that.

**Pull request closed without merging**
