### PR TITLE
[red-knot] have mdformat wrap mdtest files to 100 columns

### PR DESCRIPTION
**Pull request by carljm**
This makes it easier to read and edit (and review changes to) these files as source, even though it doesn't affect the rendering.

### CODE REVIEW

**Review by AlexWaygood — APPROVED** [review]
Thank you!! I was hoping there was a tool that would do this automatically for us

**Comment by MichaReiser** [comment]
Not sure about the limit to be 80, considering that blackendocs use 130. Also, what tiny screen do you all have :P

**Comment by AlexWaygood** [comment]
I'd be okay with increasing the limit here to 100 and reducing the blacken-docs limit to 100, if we want a consistent wrapping.

> Also, what tiny screen do you all have :P

Hehe. How do I do split-screening on my 14" laptop in a coffee shop with lines as long as you write them 😆

**Review by MichaReiser — APPROVED** [review]
LGTM. Consider waiting till after @sharkdp's PR for unbound landed to not create more (and very annoying to that) merge conflicts for him.

What's funny about this PR is that it makes most lines longer haha

**Comment by sharkdp** [comment]
> LGTM. Consider waiting till after @sharkdp's PR for unbound landed to not create more (and very annoying to that) merge conflicts for him.

Apparently, there are no conflicts. But thanks for waiting!

**Pull request merged**
