### PR TITLE
PLW1501

### PR DESCRIPTION
**Pull request by aspizu**
#970

### CODE REVIEW

**Review by charliermarsh — COMMENTED** [review]
Before I review, do you mind adding test coverage for this rule via test fixture file?

**Comment by aspizu** [comment]
sorry i can't

**Comment by konstin** [comment]
Do you mean you don't know how, you don't have time to or is something else blocking you?

**Comment by aspizu** [comment]
I'd prefer to work on other things.

**Comment by konstin** [comment]
What are your plans for #7770? I think this would also need a test file for us to be able to review and merge

**Pull request closed without merging**
