### PR TITLE
[`ruff`] - allow private variables for `RUF006`

### PR DESCRIPTION
**Pull request by diceroll123**
## Summary

Changes RUF006 to allow private vars.

I believe this is a reasonable addition, private declarations surely satisfy the underlying needs.

## Test Plan

`cargo test`

### CODE REVIEW

**Review by MichaReiser — COMMENTED** [review]
We should document this pattern and explain the reasoning why we allow it. 

To me it's not entirely clear if allowing it is in the spirit of the rule. I suspect you're coming from rusts `let _ = returns_result()` convention that allows suppressing the `must_use` error?. 

@AlexWaygood any thoughts?

**Review by AlexWaygood — APPROVED** [review]
@MichaReiser this makes sense to me. This rule isn't a stylistic rule, it's a correctness rule. You need to have a reference to the `asyncio` task or it will be garbage collected, which isn't what you want. From the perspective of Python's garbage collector, it doesn't matter whether you assign it to a private name or a public name.

In my opinion, the docs for this rule already explain the motivation for the rule quite well, so I don't think extra documentation is required here

**Comment by AlexWaygood** [comment]
I discussed this offline with @MichaReiser and I think I misunderstood what this PR was trying to do.

@diceroll123, the fixture snippet you've added looks like this:

```py
import asyncio

def f():
    loop = asyncio.get_event_loop()
    _task = loop.create_task(main())
```

Ruff will indeed emit a RUF006 error on this currently, but it's not because it's a private variable. It's because the function could exit immediately after the `loop.create_task()` call, which will lead to the `_task` variable immediately being cleaned up since it's only a local variable. If you change your example to this, Ruff no longer complains about it:

```py
import asyncio

def f():
    global _task
    loop = asyncio.get_event_loop()
    _task = loop.create_task(main())
```

I'm no longer convinced I agree with the change being proposed here. I think the bug that the rule is trying to protect you from applies just as much to tasks assigned to variables that start with underscores. Could you maybe give a little more detail about your motivation for making this PR?

**Comment by diceroll123** [comment]
Hm, good points all around.

The usage in my codebase that made me make this PR is deep within a forever-running async loop, so I suppose I overlooked what Alex has brought up.

**Pull request closed without merging**
