### PR TITLE
ruff_python_formatter: add test for extraneous info string text

### PR DESCRIPTION
**Pull request by BurntSushi**
@ofek asked [about this][ref]. I did specifically add support for it, but neglected to add a test. This PR adds a test.

[ref]: https://github.com/astral-sh/ruff/pull/9030#issuecomment-1846054764

### CODE REVIEW

**Review by charliermarsh — APPROVED** [review]
Nice

**Review by MichaReiser — APPROVED** [review]
TIL that you can have additional text after the language specifier

**Comment by ofek** [comment]
Not in pure Markdown but extensions do support that frequently to do various things!

**Comment by BurntSushi** [comment]
> Not in pure Markdown but extensions do support that frequently to do various things!

Assuming pure Markdown is CommonMark, the extra text after the opening fences is called the "info string" and it does indeed permit for pretty much anything to go there. There are even examples in the spec: See: https://spec.commonmark.org/0.30/#fenced-code-blocks

The spec doesn't attach any semantic value to any part of the "info string," it just specifies what is allowed there. For example, when using backticks for a fenced code block, the info string itself cannot contain backticks. But it can if you use tildes!

**Pull request merged**
