### PR TITLE
Indicated Successful Check

### PR DESCRIPTION
**Pull request by vinhocent**
## Summary

Adds a successful check message after no errors were found 
Implements #8553 

## Test Plan

Ran a check on a test file with `cargo run -p ruff_cli -- check test.py --no-cache` and outputted as expected.

Ran the same check with `cargo run -p ruff_cli -- check test.py --no-cache --silent` and the command was gone as expected.

### CODE REVIEW

**Comment by vinhocent** [comment]
I'm wondering how to add the counting for the number of files checked - I see that it lives in `check.rs` here but this stat isn't available in diagnostics, is it?

image

**Comment by vinhocent** [comment]
Also in the case of tests like this:
image


Do we even want to output a successful check?

**Comment by konstin** [comment]
No, we should fail there but currently don't

**Comment by nm-remarkable** [comment]
This might cause issues with `pre-commit` since that framework uses "any message at the output" as error. Or bash pre-commit hooks.

**Comment by hughhan1** [comment]
> No, we should fail there but currently don't

@konstin, by "fail", do you specifically mean that we should be exiting with a non-zero exit code? And perhaps continuing to have nothing dumped to `stdout`?

**Comment by konstin** [comment]
> by "fail", do you specifically mean that we should be exiting with a non-zero exit code? 

yes

**Review by zanieb — APPROVED** [review]
@konstin this seems very simple, my only thought is maybe we should have a different message that's in a different format so it's obviously distinct e.g. "No errors found" (I don't love exact message that since it sounds like an error)

@charliermarsh any ideas?

I'd also like to say how many files we scanned e.g. "Found 0 errors in 125 files" would be helpful to know it actually scanned something. We can track that separately.

**Comment by konstin** [comment]
Slight preference for something like "All checks passed" over something that contains the word error, otherwise i'm on board.

**Comment by zanieb** [comment]
I like "All checks passed" although it's a little outside our normal terminology

**Comment by silverwind** [comment]
Is there an option to disable this? All my other linters are silent on success, so ruff sticks out like a sore thumb. `-q` does not work because it would also suppress errors which should stay visible.

```
poetry run ruff check src
All checks passed!          // why so verbose?
poetry run yamllint .
npx eslint ui
npx stylelint ui
```

**Comment by zanieb** [comment]
I'm not sure what to say here. A configuration option for this seems excessive and it is significantly friendlier for Ruff to indicate that it _did_ something. If you want to open an issue requesting a configuration option, we can consider it. I'd want to see significant community feedback that this is important first though.

**Comment by silverwind** [comment]
Sorry, I figured out that `-q` actually works as expected and suppresses it just fine, so nothing to do and sorry for the noise :)

**Comment by zanieb** [comment]
Oh great! :)

**Comment by alexeagle** [comment]
> that framework uses "any message at the output" as error

https://github.com/aspect-build/rules_lint/blob/main/docs/lint_test.md is one such tool. It is used by Bazel users to assert "no warnings were produced by the tool". So this change broke our tests. From what I can tell, ruff is the only linter we integrate that prints on success.

> issue requesting a configuration option, we can consider it. I'd want to see significant community feedback that this is important

Here's some other linter decisions on this:
- https://github.com/golangci/golangci-lint/issues/121 - always be silent following https://www.linfo.org/rule_of_silence.html
- https://github.com/eslint/eslint/issues/3495#issuecomment-133820141 - eslint is incredibly widely adopted and the person commenting here is one of the most prolific and respected developers in the Node.js ecosystem.
- From the (still open?) issue requesting this change, the author observes
  "On the other hand, several linters are silent if they find nothing (pycodestyle, flake8, isort, etc.)."

So I think rather than add an option, ruff should go back to the old silent-on-success behavior.

**Comment by MichaReiser** [comment]
@alexeagle would you mind creating a new issue for this to avoid having discussions on merged PRs. Thank you

**Comment by alexeagle** [comment]
@MichaReiser thanks for the quick reply, since the issue requesting this change is still open, I've just commented there: https://github.com/astral-sh/ruff/issues/8553#issuecomment-2022771565

**Comment by zanieb** [comment]
Thanks for moving the discussion!

**Pull request merged**
