### PR TITLE
[`pylint`] - Add `unreachable` rule (`W0101`)

### PR DESCRIPTION
**Pull request by diceroll123**
## Summary

Add `unreachable`, shows where the end of the current body's unreachable code is.

See: #970

## Test Plan

`cargo test` _and a lot of crying because of late night recursion woes_

### CODE REVIEW

**Comment by diceroll123** [comment]
Not sure what's causing this possible range error 🤔

**Comment by charliermarsh** [comment]
I'd prefer to support this by restoring and finishing our control-flow graph implementation: https://github.com/astral-sh/ruff/pull/5384. I think that abstraction will be more robust, and will also be useable in other parts of Ruff. Are you interested in looking into it?

**Comment by diceroll123** [comment]
oo, that's a big one, I'll possibly give it a whack sometime. For now I'll make this PR a draft.

**Comment by MichaReiser** [comment]
I close this PR as there hasn't been any progress in a while, and I agree with @charliermarsh that we need to build out a more holistic infrastructure for this.

Feel free to re-open it if you plan to work on this.

**Pull request closed without merging**
