### PR TITLE
Use `deflate` on PowerPC

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

I think this should work... But it's hard to test (see: https://github.com/conda-forge/ruff-feedstock/pull/219). AFAICT, those builds still happen on an X86 machine, so it should be okay that the build script _depends_ on zstd, as long as it doesn't have to pull it in.

### CODE REVIEW

**Comment by zanieb** [comment]
Tested at https://github.com/conda-forge/ruff-feedstock/pull/220

**Comment by charliermarsh** [comment]
Alas

**Comment by charliermarsh** [comment]
Three options:

1. Don't use zstd even when building for PowerPC (remove it from the build script).
2. Stop supporting PowerPC for now.
3. Find a way to fix the build issue on conda-forge (best but least unsure how to do).

**Comment by charliermarsh** [comment]
Current version of the PR attempts (1), lets see if it makes a difference.

**Comment by charliermarsh** [comment]
I don't really get it, but that also didn't work. I think because the host machine target triple isn't PowerPC?

**Comment by MichaReiser** [comment]
You also need to change the build.rs here

https://github.com/astral-sh/ruff/blob/6c303b24455f26ff08859affc080e43e1206ea6c/crates/red_knot_python_semantic/build.rs#L33

**Comment by MichaReiser** [comment]
I guess the problem here is that conda cross compiles to power pc. That's why the conditional target_arch build dependencies don't work

**Pull request closed without merging**
