### PR TITLE
Apply consistent code block labels

### PR DESCRIPTION
**Pull request by doolio**
This ensures the python label is used for all python code blocks for consistency.

## Test Plan

Visual inspection of all changes via git client ensuring no other changes were made in error.

### CODE REVIEW

**Comment by doolio** [comment]
I don't know why these checks fail. I don't think it is related to the changes I made.

**Comment by zanieb** [comment]
@doolio you edited a bunch of our test snapshots in which ```py is generated

https://github.com/astral-sh/ruff/blob/317d3dd61218bcc35b20a42403f3c9acc1963be2/crates/ruff_python_formatter/tests/fixtures.rs#L267

**Comment by doolio** [comment]
Oh ok. So I should not have made the changes in the `.snap` files? I made this PR because I noticed there were many more instances of ` ```python` than ` ```py` code blocks across the codebase even in the `.rs` files.

If I change the string from "py" to "python" in the following and equivalent lines would that allow these checks to pass?

https://github.com/astral-sh/ruff/blob/3ebaca52464e1db3d808adca9c3de09b90dabfaf/crates/ruff_python_formatter/tests/fixtures.rs#L74

If these changes are unwelcome feel free to close this PR.

**Comment by zanieb** [comment]
> So I should not have made the changes in the .snap files? 

Yeah the snapshots are generally updated by `cargo insta test` and `cargo insta review`.

This pull request would be simpler if you didn't touch those files, I'm not sure if we care about the language header there cc @konstin 

> If I change the string from "py" to "python" in the following and equivalent lines would that allow these checks to pass?

They might — I'm not sure of all the details for the formatter test fixtures without trying it.

> If these changes are unwelcome feel free to close this PR.

They seem reasonable!

**Comment by konstin** [comment]
Changing `CodeFrame::new("py"` to `CodeFrame::new("python"` and then running the test should give the desired formatting, i'm in favor of changing the snapshot files for consistency. You don't need to edit the snap file automatically, they are generated by [insta](https://insta.rs/).

**Comment by doolio** [comment]
OK cool. Is it simpler then for me to close this PR and create a new one?

**Comment by charliermarsh** [comment]
It's ok for it to be part of this PR. You can change the reference above, and then run `cargo test` followed by `cargo insta review`. It should ask you about each snapshot change, and you can confirm them all, then check in the changes and push.

**Comment by doolio** [comment]
> then run `cargo test` followed by `cargo insta review`. 

`cargo test` seems to have run without issue but I get the following error trying to run the second command.

image

I can confirm though `insta-1.34.0` is in my `cargo` registry. 

I installed `cargo-insta` (necessary?) and re-ran both commands. Again the tests passed without issue but I now get the following output from the second command.

image

**Comment by charliermarsh** [comment]
@doolio - They may be nothing to review because you already modified the snapshots themselves. (Typically, if you change something, you run tests, then run `cargo insta review` to review and accept the changes.)

**Comment by charliermarsh** [comment]
Anyway, this looks good to me! Thanks!

**Pull request merged**
