### PR TITLE
Add hidden `--parser` option to override the input format, rather than inferring it from the file extension

### PR DESCRIPTION
**Pull request by felix-cw**
## Summary

This adds a hidden `--parser` option to the `check` command, motivated by #6847. 
This option allows overriding the input format of the code, rather than inferring from the file extension.

The possible values are `py` and `ipynb`. If `--parser` is not specified, file formats are inferred from file extensions.

## Test Plan

- Added tests in `integration_tests.rs` to ensure the parser override worked as expected.

### CODE REVIEW

**Comment by charliermarsh** [comment]
This is really nice work. Let me try to get some alignment on what we want this argument to be called in the originating issue, since there was some discussion there still...

**Comment by charliermarsh** [comment]
(Assigning myself as reviewer.)

**Comment by felix-cw** [comment]
Thanks for the kind comment! I'm thinking that the preferred idea in the discussion is to provide an option that maps file extensions to language, whereas this just overrides the language for everything. Please don't hesitate to close this PR if this is the wrong approach.

**Comment by felix-cw** [comment]
I'm closing this PR in favour of  #8373 which seems to be a more sensible approach.

**Pull request closed without merging**
