### PR TITLE
Fix TODO directive out of bounds acccess

### PR DESCRIPTION
**Pull request by MichaReiser**
## Summary

Fixes an out of bound access that I introduced https://github.com/astral-sh/ruff/pull/13640 where the old code was incorrect too, because it didn't handle joined comments correctly.

This PR fixes the out of bound access and adds a test for joined comments (`# test # TODO: fixme`).

Fixes https://github.com/astral-sh/ruff/issues/13755

## Test Plan

See added tests

### CODE REVIEW

**Review by dhruvmanila — APPROVED** [review]
Looks good. The ecosystem checks seems unrelated.

**Comment by MichaReiser** [comment]
Hmm, what's up with our ecosystem checks. Let me re-run

**Comment by MichaReiser** [comment]
Okay I don't know what's happening lol.

**Comment by dhruvmanila** [comment]
It's interesting that the number of additions in this PR is quite close to the number of removals in https://github.com/astral-sh/ruff/pull/13640#issuecomment-2395004667.

**Comment by MichaReiser** [comment]
> It's interesting that the number of additions in this PR is quite close to the number of removals in [#13640 (comment)](https://github.com/astral-sh/ruff/pull/13640#issuecomment-2395004667).

Yes... the PR should not have removed any violations. I expect that it was panicking for all those repos, which is why there are so many changes. I ran the ecosystem check locally against the commit before I merged that PR and the result is:

<details><summary><a href="https://github.com/zulip/zulip">zulip/zulip</a> (+0 -7 violations, +0 -0 fixes)</summary>
<p>
<pre>ruff check --no-cache --exit-zero --ignore RUF9 --output-format concise --no-preview --select ALL</pre>
</p>
<p>

<pre>
- <a href='https://github.com/zulip/zulip/blob/3ccd53ce20c799debec45e1c806704c4e2589c10/zerver/actions/create_realm.py#L239'>zerver/actions/create_realm.py:239:11:</a> FIX004 Line contains HACK, consider resolving the issue
- <a href='https://github.com/zulip/zulip/blob/3ccd53ce20c799debec45e1c806704c4e2589c10/zerver/management/commands/list_realms.py#L56'>zerver/management/commands/list_realms.py:56:15:</a> FIX004 Line contains HACK, consider resolving the issue
- <a href='https://github.com/zulip/zulip/blob/3ccd53ce20c799debec45e1c806704c4e2589c10/zerver/tests/test_queue_worker.py#L423'>zerver/tests/test_queue_worker.py:423:11:</a> FIX004 Line contains HACK, consider resolving the issue
- <a href='https://github.com/zulip/zulip/blob/3ccd53ce20c799debec45e1c806704c4e2589c10/zerver/tests/test_slack_importer.py#L1244'>zerver/tests/test_slack_importer.py:1244:15:</a> FIX004 Line contains HACK, consider resolving the issue
- <a href='https://github.com/zulip/zulip/blob/3ccd53ce20c799debec45e1c806704c4e2589c10/zerver/views/realm_icon.py#L65'>zerver/views/realm_icon.py:65:7:</a> FIX004 Line contains HACK, consider resolving the issue
- <a href='https://github.com/zulip/zulip/blob/3ccd53ce20c799debec45e1c806704c4e2589c10/zerver/views/realm_logo.py#L68'>zerver/views/realm_logo.py:68:7:</a> FIX004 Line contains HACK, consider resolving the issue
- <a href='https://github.com/zulip/zulip/blob/3ccd53ce20c799debec45e1c806704c4e2589c10/zilencer/management/commands/populate_db.py#L109'>zilencer/management/commands/populate_db.py:109:7:</a> FIX004 Line contains HACK, consider resolving the issue
</pre>

</p>
</details>
<details><summary>Changes by rule (1 rules affected)</summary>
<p>

| code | total | + violation | - violation | + fix | - fix |
| ---- | ------- | --------- | -------- | ----- | ---- |
| FIX004 | 7 | 0 | 7 | 0 | 0 |

</p>
</details>

**Pull request merged**
