### PR TITLE
[`refurb`] Implement `repeated-global` (`FURB154`)

### PR DESCRIPTION
**Pull request by alex-700**
## Summary

Implement repeated_global (FURB154) lint.
See:
- https://github.com/astral-sh/ruff/issues/1348
- [original lint](https://github.com/dosisod/refurb/blob/master/refurb/checks/builtin/simplify_global_and_nonlocal.py)

## Test Plan
cargo test

### CODE REVIEW

**Comment by charliermarsh** [comment]
Since globals and nonlocals are rare, could we try instead running this rule on every `global` and `nonlocal` statement, and then, for each statement, mapping back to the containing `Suite` and looking for `global` statements that follow it repeatedly?

In other words... instead of iterating over every body / statement, can we instead run this for each `global`? You can look at `traversal::next_sibling` or `traversal::suite` (and their usages) for an example.

**Comment by alex-700** [comment]
> Since globals and nonlocals are rare, could we try instead running this rule on every `global` and `nonlocal` statement, and then, for each statement, mapping back to the containing `Suite` and looking for `global` statements that follow it repeatedly?
> 
> In other words... instead of iterating over every body / statement, can we instead run this for each `global`? You can look at `traversal::next_sibling` or `traversal::suite` (and their usages) for an example.

@charliermarsh done.
Just a note: now the algorithm is quadratic on `len(suite)` for each suite containing `global` or `nonlocal`. Instead of linear (and should be auto vectorized) for each suite.

**Comment by charliermarsh** [comment]
Thanks @alex-700. Blocked on me, will review shortly.

**Review by charliermarsh — APPROVED** [review]

**Comment by charliermarsh** [comment]
I'm confused by the CodSpeed results but my guess is it's just confused by the branch being dated? We didn't touch the parser or lexer here of course.

**Pull request merged**
