### PR TITLE
[`pylint`] Implement Pylint `bad-format-character` (`E1300`)

### PR DESCRIPTION
**Pull request by silvanocerza**
## Summary

Relates to #970.

Add new `bad-format-character` Pylint rule.

I had to make a change in `crates/ruff_python_literal/src/format.rs` to get a more detailed error in case the format character is not correct. I chose to do this since most of the format spec parsing functions are private. It would have required me reimplementing most of the parsing logic just to know if the format char was correct.

This PR also doesn't reflect current Pylint functionality in two ways.

It supports new format strings correctly, Pylint as of now doesn't. See pylint-dev/pylint#6085.

In case there are multiple adjacent string literals delimited by whitespace the index of the wrong format char will relative to the single string. Pylint will instead reported it relative to the concatenated string.

Given this:
```
"%s" "%z" % ("hello", "world")
```

Ruff will report this:
```Unsupported format character 'z' (0x7a) at index 1```

Pylint instead:
```Unsupported format character 'z' (0x7a) at index 3```

I believe it's more sensible to report the index relative to the individual string.

## Test Plan

Added new snapshot and a small test in `crates/ruff_python_literal/src/format.rs`.

### CODE REVIEW

**Comment by silvanocerza** [comment]
No idea why the `cargo test (wasm)` is failing. 
I tried running it locally using `wasm-pack` version `0.12.1` and it didn't fail.
Also I see no other PRs failing cause of that.

**Comment by charliermarsh** [comment]
(I think the wasm test is just a little flaky, I've seen that failure before.)

**Comment by charliermarsh** [comment]
Awesome, thank you! I made a few minor changes, including only running the `.format()` version if the it's part of a `.format()` call.

I also dropped the index reporting for now... I'm worried that we'll get it wrong in some cases due to the string preprocessing that happens in the parser (for the `.format()` case), which you hinted at above (with regards to the `%` case, where we use the token stream). I know it's not parity with pylint, but it seems ok to me for now... If you feel strongly, I'm obviously happy to revisit :)

**Comment by charliermarsh** [comment]
There's also at least one false negative which I've documented in the tests: `print(("%" "z") % 1)`

**Comment by silvanocerza** [comment]
No worries, I appreciate the feedback and the tweak. I'm still learning Rust looking at those certainly helps.

Though I'm wondering if the snapshot is correct. I see no new style formatting reports. Does the new logic actually catch both f-strings and `.format()`?

**Comment by charliermarsh** [comment]
Thanks, I missed that! Added here: https://github.com/astral-sh/ruff/pull/6340. (It doesn't fire for f-strings, but it didn't before either IIRC.)

**Comment by silvanocerza** [comment]
No worries. 
In any case it was working for f-strings too though cause it was firing for string constant instead of expr calls.

**Pull request merged**
