### PR TITLE
Fix Indexer fails to identify continuation preceded by newline #10351

### LINKED ISSUE #10351: `Indexer` fails to identify continuation preceded by newline
Given:

```python
(
    1
    \
    + 2)
```

We don't identify any `continuation_lines` in the `Indexer`.

### PR DESCRIPTION
**Pull request by augustelalande**
## Summary

Fixes #10351

It seems the bug was caused by this section of code
https://github.com/astral-sh/ruff/blob/b669306c87ec304182fd50872b50858e2faf0262/crates/ruff_python_index/src/indexer.rs#L55-L58

It's true that newline tokens cannot be immediately followed by line continuations, but only outside parentheses. e.g. the exception
```
(
    1
    \
    + 2)
```

But why was this check put there in the first place? Is it guarding against something else?

## Test Plan

New test was added to indexer

### CODE REVIEW

**Comment by charliermarsh** [comment]
Can you find anything via `git blame` about why this is here?

**Comment by charliermarsh** [comment]
(It's possible that something changed in the lexer over time that made this not necessary.)

**Comment by augustelalande** [comment]
This was the original implementation
https://github.com/astral-sh/ruff/blob/3791ca721aca9af04929d8caaa4678f0e252fbc3/src/source_code/indexer.rs#L22-L48
which had slightly different logic and needed the check to avoid flagging every newline. The checks just got kept through the edits.

Note: This implementation would also have failed to parse the code in question correctly.

**Comment by charliermarsh** [comment]
Okay, I think it was this change, long ago: https://github.com/RustPython/Parser/pull/27

**Pull request merged**
