### PR TITLE
[flake8-type-checking] Fix false positives for `typing.Annotated`

### PR DESCRIPTION
**Pull request by Daverball**
This partially addresses #13713

## Summary

Ruff properly clears  the `TYPE_DEFINITION` flag when visiting special parts of an annotation like `typing.Literal` and `typing.Annotated`. However there are other typing related semantic flags which aren't cleared. This is fine, however `is_typing_reference` only check for those higher level flags and completely ignores `TYPE_DEFINITION`, which can lead to false positives for TCH001-003.

## Test Plan

`cargo nextest run`

### CODE REVIEW

**Comment by MichaReiser** [comment]
@AlexWaygood would you mind taking a look at this PR? I think you have a better understanding of our type checking flags

**Comment by Daverball** [comment]
Not quite sure what the new LOG015 violations are about and how they are related to this change, but they look correct to me.

The RUF100 violations are encouraging, since these are all due to previous false positives.

**Comment by MichaReiser** [comment]
@Daverball can you try rebasing/merging main. I suspect that will help with the `LOG015` ecosystem changes

**Review by AlexWaygood — APPROVED** [review]
Thank you! This LGTM.

**Comment by dhruvmanila** [comment]
@AlexWaygood I'm assuming this is a bugfix based on the PR title but feel free to update the label if you think it's a rule change.

**Comment by AlexWaygood** [comment]
> @AlexWaygood I'm assuming this is a bugfix based on the PR title but feel free to update the label if you think it's a rule change.

Yes, I think that's right! Sorry, I should have added the label.

**Pull request merged**
