### PR TITLE
[`pycodestyle`] Add E122 rule ("continuation line missing indentation or outdented")

### PR DESCRIPTION
**Pull request by hoel-bagard**
## Summary

This PR is part of https://github.com/charliermarsh/ruff/issues/2402, it aims to add the `E12` rules, starting with `E122`, along with their fixes.

## Test Plan

The test fixture uses [the one from pycodestyle](https://github.com/PyCQA/pycodestyle/blob/main/testing/data/E12.py
).

## Discussion

I am opening a draft PR while implementation is not done yet in order to be able to receive advice before proceeding.

Implementing the rule using logical lines seems natural (and that is what pycodestyle does). It seems like it would work for continuation lines made using parentheses since a `NonLogicalNewline` is emitted for the new line.
However, when using a backslash (case covered by pycodestyle), no `NonLogicalNewline` token is created, rendering it impossible to know if there is a newline within the logical line.

Could a `NonLogicalNewline` be emitted when there is a backslash, or should the rule be implemented using physical lines (or another method) ?

Example with parentheses:
```python
print("E122", (
"dent"))
```

Example using a backslash:
```python
if some_very_very_very_long_variable_name or var \
or another_very_long_variable_name:
    raise Exception()
```

### CODE REVIEW

**Comment by charliermarsh** [comment]
Have you taken a look at how pycodestyle solves this problem, given that the `\` doesn't emit a token?

You could also take advantage of the fact that if you see a newline character _without_ a `Tok::Newline` or `Tok::NonLogicalNewline`, then it must be a continuation. We take advantage of this in the `Indexer` struct.

**Comment by hoel-bagard** [comment]
The pycodestyle solution rely on the fact that each token contains the physical line number it is on, therefore I can't use their approach.
However I can look for newline characters like in the Indexer.

Thank you for the help.

**Comment by hoel-bagard** [comment]
The changes from the PR seem to be slow, I'm guessing that the `get_token_infos` is the slow part, but it was needed to implement rule `E122` the same way as pycodestyle. It will also be useful when implementing the other `E12` rules. Is there a way to implement it that would be faster ?

Part of the code is meant to be used for the other `E12` rules, since at first I thought about also adding them in this PR. However, the pycodestyle implementation does not detect anything for `E121`, `E123` and `E126`, so I will add them in a separate PR (if this PR is accepted). I tried to remove most of the code directly linked to the other rules, but there are still traces of it in some complex and empty ifs.

**Comment by hoel-bagard** [comment]
Closed in favor of #8557

**Pull request closed without merging**
