### PR TITLE
docs: show nursery icon for nursery rules

### PR DESCRIPTION
**Pull request by akx**
## Summary

This changes the docs to show a nursery icon (🌅) for rules in the nursery.

It currently doesn't do that for the rules that are in sub-categories (Pylint, Pycodestyle) because there is no `all_rules()` for the `RuleCodePrefix` that's returned by `UpstreamCategory` iteration (and as mentioned on Discord, I think `UpstreamCategory` maybe shouldn't be a thing). (That would be enabled by #5591.)

## Test Plan

Generated docs to see new icons (with the caveat above).

### CODE REVIEW

**Comment by charliermarsh** [comment]
Bad reviewer hygiene as I haven't looked through the code at all, but I only have a minute tonight so want to chime in to say, it probably _is_ important that we support this for the pycodestyle rules, since we have a bunch of nursery rules in there that I'd love to get in the docs.

**Comment by akx** [comment]
> Bad reviewer hygiene as I haven't looked through the code at all, but I only have a minute tonight so want to chime in to say, it probably _is_ important that we support this for the pycodestyle rules, since we have a bunch of nursery rules in there that I'd love to get in the docs.

Absolutely! (Those are the ones I'm interested in tbh.) I'm just not perfectly sure how to best do that, since I don't know how to add `all_rules()` from #5436 into `RuleCodePrefix` (as returned by the `UpstreamCategory` iteration), and that led me to thinking whether the whole `UpstreamCategory` thing should just be replaced by rules having optional `RuleCategory`s...

**Comment by charliermarsh** [comment]
I took another look at this to try and get the pycodestyle rules to show, and it's just really tough to work with the proc macro code.

**Comment by akx** [comment]
@charliermarsh See #5591 – it's not quite perfect but does the trick here 😅

**Pull request merged**
