### PR TITLE
Expand RUF008 to all classes, but to a new code (RUF012)

### PR DESCRIPTION
**Pull request by adampauls**
AFAIK, there is no reason to limit RUF008 to just dataclasses -- mutable defaults have the same problems for regular classes. 

Partially addresses https://github.com/charliermarsh/ruff/issues/4053 and broken out from https://github.com/charliermarsh/ruff/pull/4096.

### CODE REVIEW

**Comment by madkinsz** [comment]
With dataclasses, it is not apparent that a value will be shared across all of the instances. However, that is a special case. For class attributes, it is normal for a value to be shared across all of the instances. That's often the _reason_ that you would use a class attribute instead of assigning the value in `__init__`. For example, one of the few cases where I use class attributes is for tracking instances of the class

```python
class Foo:
    _instances = []
    
    def __init__(self):
        self._instances.append(self)
```

If you're interested in adding a rule for this, please make it a separate rule as is quite distinct from the dataclass case.

**Comment by adampauls** [comment]
My understanding was that `ClassVar` exists precisely to precisely to [address the confusion](https://peps.python.org/pep-0526/#class-and-instance-variable-annotations) between class and instance variables. It's true that if you enable RUF008 but are not in a codebase with type hints, you might have a bad time, but that seems okay to me?

> This is only unclear when using dataclasses because the class attributes are being used to magically define instance construction.

I think this is not quite true. If you put `x: int = 5` on any class (dataclass or not), then there is an instance variable as well as a class variable:
```
>>> class Foo:
...   x: int = 5
...
>>> f = Foo()
>>> f.x=6
>>> f.x
6
>>> Foo.x
5
>>> import dataclasses
>>> @dataclasses.dataclass
... class DFoo:
...   x: int = 5
...
>>> DFoo(7)
DFoo(x=7)
>>> d = DFoo(7)
>>> d.x=6
>>> d.x
6
>>> DFoo.x
5
>>> DFoo.x=4
>>> d.x
6
>>> DFoo.x
4
>>> Foo.x=4
>>> Foo.x
4
>>> f.x
6
```

I think the reason that the original rule was written for dataclasses is that people do not commonly use attribute declarations outside of dataclasses, but I think that's more "cultural" than anything. You're probably right that outside of dataclasses, there's a pretty good chance that if have a `x: int = 5`, you are probably using it as a class variable, even though if is in fact just as much an instance variable as a class variable.

I think it's okay to have this rule and have people use `ClassVar` to declare when they are doing that, but I'm happy to be overruled and make this a separate rule.

**Comment by madkinsz** [comment]
Thanks for taking the time to expand on your viewpoint!

Perhaps a compelling reason to make them different rules is that the suggestion is different:

- For dataclasses, mutable attributes should use `field(default_factory=...)` or (rarely) use `ClassVar`
- For classes, mutable attributes should use `ClassVar` or be changed to instance variables (assigned in `__init__`)

I see use of class variables on dataclasses as a bit of an antipattern and would be hesitant to suggest it to most users.

**Comment by adampauls** [comment]
@madkinsz I think you are saying that class attributes "should" only be used as instance variables for dataclasses and as class variables for non-dataclasses, even though in fact, class attributes are (very confusingly!) always both in either case. You may or may not be right that the Python community does that in practice. I'll just note that RUF008 already explicitly exempts ClassVars from the mutability check, indicating that at `ruff` does not currently take the position that ClassVars are so rare for dataclasses. I think, culturally, the type of people who use `ruff` to catch bugs will be okay annotated class variables on non-dataclasses with `ClassVar[Any]` if they have to. 

I'll also just say that this whole class/instance variable thing is even worse than you think! An expanded example from PEP 526:
```python
    class Starship:
        captain: str = "Picard"
        damage: int
        stats: ClassVar[dict[str, int]] = {}

        def __init__(self, damage: int, captain: str | None = None) -> None:
            self.damage = damage
            if captain:
                self.captain = captain  # Else keep the default

        def hit(self):
            Starship.stats["hits"] = Starship.stats.get("hits", 0) + 1

    enterprise_d = Starship(3000)
    enterprise_c = Starship(2000)

    # pyright -- error: Cannot assign member "stats" for type "Starship"
    # HOWEVER, this still makes a new instance variable!
    enterprise_d.stats = {}
    Starship.stats = {}  # This is OK
    enterprise_d.stats["foo"] = 1  # this is okay for pyright and only mutates the new instance variable on enterprise_d
    enterprise_c.stats["foo"] = 2  # this is okay for pyright, but mutates the class variable
    print(Starship.stats)  # prints {'foo': 2}
```

Even `pyright` can't save us from the madness! I know this example doesn't exactly help my case, since this PR would not catch any of the confusing behavior in this example. At the same time, this behavior is even more confusing if you don't declare `stats` to be a `ClassVar`.

My point is just that the behavior here is all very confusing and I think it is nice to be able to say that mutable non-`ClassVar `class attributes should just never be used, hence the new RUF008. Happy to break it out into two rules if @charliermarsh prefers though.

**Comment by charliermarsh** [comment]
Hey sorry -- I know I'm being looked to for an opinion here, it's on my TODO list!

**Comment by charliermarsh** [comment]
Okay, sorry, I finally got time to read through this in detail -- thank you both for the thoughtful analysis above.

I tend to agree with @madkinsz that dataclasses are materially different from other classes, and that if we do pursue these, they should be implemented as separate rules. However, I'm not yet convinced that we _should_ add those separate rules in the first place. Using mutable class attributes is a common and reasonable convention in Python.

The furthest I'd go, I think, is to flag mutable class attributes that _aren't_ annotated with `ClassVar` (and exempt dataclasses from this check, since they should be enforced with the existing rules, and we'd like to avoid duplicate diagnostics). I know that `ClassVar` actually connotes something slightly different ("This shouldn't be assigned on individual instances", whereas here we're treating it as "This is known to be mutable and shared across classes" -- you could imagine a hypothetical situation in which someone wants a mutable class attribute, like a shared `dict`, but also wants to allow individual instances to override with their own `dict`; but that strikes me as an odd pattern, and this is a linter, we can be opinionated about the patterns that we flag and don't).

Does that seem useful to folks? Too limited to be useful?

Either way, before merging, I'd want to see what violations that rule surfaces on the ecosystem CI check or on a broader set of repos (\cc @konstin), which is really something we should be doing for all novel Ruff rules anyway.

**Comment by adampauls** [comment]
@charliermarsh I split the check for non-dataclasses out into a new rule.

**Comment by konstin** [comment]
To better understand the impact of this change, i ran RUF011 against the scraped ecosystem dataset: https://gist.github.com/konstin/7391392ca16747031aa1b0c314568f21. Naturally, there's a lot of noise there (e.g. i've seen some migration files being flagged).

Background: The dataset includes 3408 github projects using ruff from [akx/ruff-usage-aggregate](https://github.com/akx/ruff-usage-aggregate/blob/4adc8337aeb1e6da3570cfbb6d2581800ff73084/data/known-github-tomls-clean.jsonl), 1174 contain at least one RUF011 violations. I ran the analysis with `scripts/ecosystem_all_check.sh check --select RUF011` and collected the results with `rg ": RUF011" target/ecosystem_all_results/*.stdout.txt > target/RUF011.txt`. The repositories use the default branch of each repository as of 2023-05-24.

The normal ecosystem ci should create a more concise report for a small number of handpicked projects, but i think it's currently skipped as cargo test is failing.

**Comment by adampauls** [comment]
Oops, fixed `cargo test`.

**Comment by adampauls** [comment]
I spot checked a few of the flags in the ecosystem. It looks like there are some cases where folks are using dataclass-like classes (like `pydantic.BaseModel`, indirectly inherited [here](https://github.com/logspace-ai/langflow/blob/dev/src/backend/langflow/interface/prompts/custom.py#L68)) and just plain old classes with mutable defaults (like [here](https://github.com/apache/airflow/blob/main/airflow/www/views.py#L4485-L4493)). They all look to me like they are meant to be instance defaults and could have the same gotcha behavior as for dataclasses.

**Comment by adampauls** [comment]
@charliermarsh is this on the TODO list? Or should I close?

**Comment by madkinsz** [comment]
🎉 thanks @adampauls!

**Pull request merged**
