### PR TITLE
[`ruff`] Implement `mutable-fromkeys-value` (`RUF024`)

### LINKED ISSUE #4613: Warn about `dict.fromkeys(keys, mutable)`
`ruff` should error and suggest the following fix when passing a mutable 2nd arg to `dict.fromkeys()` since modifications will affect all keys which is a common pitfall.

```py
# bad
dict.fromkeys((1, 2), {})
dict.fromkeys((1, 2), [])
dict.fromkeys((1, 2), set())
# ...

# good
{key: {} for key in (1, 2)}
{key: [] for key in (1, 2)}
{key: set() for key in (1, 2)}
```

Examples:
- [StackoverFlow](https://stackoverflow.com/q/11509721)
- [SO 2](https://stackoverflow.com/q/8174723)
- [commit](https://github.com/CederGroupHub/chgnet/commit/c8ba05443280c280f904a7076f4635d3326bac66#diff-a7bc3c3838885a61fa9d82f50027518237bf263cbbcd33781f1176b7031f1275R184-R186)

### PR DESCRIPTION
**Pull request by tjkuson**
## Summary

Implement rule `mutable-fromkeys-value` (`RUF023`).

Autofixes

```python
dict.fromkeys(foo, [])
```

to

```python
{key: [] for key in foo}
```

The fix is marked as unsafe as it changes runtime behaviour. It also uses `key` as the comprehension variable, which may not always be desired.

Closes #4613.

## Test Plan

`cargo test`

### CODE REVIEW

**Comment by AlexWaygood** [comment]
Could you maybe use RUF024 for this? I'm using RUF023 for #9564 :)

**Comment by tjkuson** [comment]
Oops, I will change it when I am back at my desk

**Comment by Skylion007** [comment]
Can you also open an issue on this for flake8-bugbear? I'm sure they'd love to include this rule and it would make more sense with a reserved B error code. Other ruff rule suggestions have been added there and we usually migrate the rule alias.

**Comment by Skylion007** [comment]
Ah nvm, there is an issue that has been open for a while: https://github.com/PyCQA/flake8-bugbear/issues/387

**Comment by tjkuson** [comment]
Thanks for renaming the PR @AlexWaygood, didn't realise I had missed that

**Review by charliermarsh — APPROVED** [review]
Excellent work, thank you.

**Pull request merged**
