### PR TITLE
[pylint] Implement import-outside-toplevel (C0415)

### PR DESCRIPTION
**Pull request by dankleeman**
## Summary
Per #970 :
Implement pylint rule C0415: import-outside-toplevel

https://pylint.readthedocs.io/en/latest/user_guide/messages/convention/import-outside-toplevel.html

## Test Plan

With cargo test following the contribution instructions.

### CODE REVIEW

**Comment by kdebrab** [comment]
Isn´t this already covered by E402 (https://docs.astral.sh/ruff/rules/module-import-not-at-top-of-file/)?

**Comment by charliermarsh** [comment]
Ugh, so sorry -- thank you for getting involved but unfortunately there's already an open PR for this rule, which I've just been slow to merge (https://github.com/astral-sh/ruff/pull/5180). Is there any way I can help you pick out another rule to work on?

**Comment by dankleeman** [comment]
> Ugh, so sorry -- thank you for getting involved but unfortunately there's already an open PR for this rule, which I've just been slow to merge (#5180). Is there any way I can help you pick out another rule to work on?

No worries! I'd love to work on other rules. I'd happily take a shot at any rule you'd suggest.

I think my only concern picking another one on my own is the discussion on #970 that mentions not wanting to implement pylint rules that are covered by mypy: https://github.com/astral-sh/ruff/issues/970#issuecomment-1783147905

**Comment by charliermarsh** [comment]
Awesome! Here are a few that look reasonable to me:

- `bad-staticmethod-argument`
- `unnecessary-dunder-call`
- `too-many-locals`

Separately: @zanieb was actually planning to go through and move all the Mypy-overlapping rules to a separate section to avoid this issue in the future.

**Pull request closed without merging**
