### PR TITLE
[`pycodestyle`] Remove deprecated functionality from `type-comparison` (`E721`)

### PR DESCRIPTION
**Pull request by augustelalande**
## Summary

Stabilizes `E721` behavior implemented in #7905.

The functionality change in `E721` was implemented in #7905, released in [v0.1.2](https://github.com/astral-sh/ruff/releases/tag/v0.1.2). And seems functionally stable since #9676, without an explicit release but would correspond to [v0.2.0](https://github.com/astral-sh/ruff/releases/tag/v0.2.0). So the deprecated functionally should be removable in the next minor release.

resolves: #6465

### CODE REVIEW

**Comment by zanieb** [comment]
To clarify, this looks like it stabilizes the preview behavior introduced in https://github.com/astral-sh/ruff/pull/9676 correct?

**Comment by augustelalande** [comment]
Yes, sorry I wasn't clear. I updated the PR summary accordingly.

**Comment by zanieb** [comment]
Thanks this makes sense to me but we need to wait until 0.5.0 to merge.

**Review by dhruvmanila — APPROVED** [review]
The ecosystem changes looks good to me. Thanks for doing this.

**Pull request merged**
