### PR TITLE
Add days-old flag to ruff clean

### PR DESCRIPTION
**Pull request by Thomasdezeeuw**
## Summary

Change the cleaning to only include files that are of a certain age.

Based on https://github.com/astral-sh/ruff/pull/5122.

## Test Plan

Manually tested.

### CODE REVIEW

**Comment by Thomasdezeeuw** [comment]
> What's the use case for this flag? It seems that building the cache is pretty cheap. A user can, therefore, just clean the whole cache and rebuild it. I think what would be more useful (but probably still too rare to be useful) is to allow cleaning by package. However, that starts exposing implementation details.

This assumes that we switch to a global cache (https://github.com/astral-sh/ruff/pull/5122), which changes `ruff clean` to remove all caches (for all packages). For users working with multiple packages they might not want to clean the entire cache, only the unused cache file. This is to combat the general problem of the "every growing cache".

**Comment by Thomasdezeeuw** [comment]
(I completely missed this comment)

> I continue to be undecided whether we should move to a global cache. It seems to introduce more complexity. Anyway:
> 
>     * I think we should change the documentation of `clean` to make it clear that, by default, removes **all** caches, globally. This should probably go into [Use global cache directory #5122](https://github.com/astral-sh/ruff/pull/5122)

:+1: 

>     * Would it make sense to instead add a flag (similar to `cargo -p`) to specify which packages to clean?
> 
> 
> > to combat the general problem of the "every growing cache".
> 
> My understanding was that your PR adding the _last seen_ already removes old files. Does this PR address the case where a cache keeps growing after changing the settings?

Yes, for caches that are actually used. When/if we switch to a global cache dir removing a Python project will no longer remove Ruff's cache for it (as it's stored outside of the project's directory that is removed). This also true, to a lesser extend, for "packages" within the same repo, e.g. one-off files, examples and often tests. Using the current solver these are stored separately from the "main" source code. For example the FastAPI repo has 79 "packages" and thus 79 different cache files, moving the source file (e.g. an example or test) will cause the cache to be now longer used, but it won't be removed as we simple don't even look at the old cache files again.

A regular `cargo clean` will take of the above, but it will also wipe out still used caches. A `days-old` flag like this adding keep the useful caches, while removing only the unused cache files.

**Comment by Thomasdezeeuw** [comment]
Since https://github.com/astral-sh/ruff/pull/5122 wasn't merged this still has some benefit, but less so. If "packages", including tests, docs, scripts, etc., move within a repo this can remove the old cache where the current `clean` command simply removes everything (this assumes a single cache dir is used for the entire repo).

**Comment by MichaReiser** [comment]
> Since #5122 wasn't merged this still has some benefit, but less so. If "packages", including tests, docs, scripts, etc., move within a repo this can remove the old cache where the current `clean` command simply removes everything (this assumes a single cache dir is used for the entire repo).

I'll close this for now based on the decision of #5122. The new flag is less needed now that we keep the local cache and cleaning the whole cache of a single project and rebuilding it should only take a few seconds. Not having the flag keeps Ruff's complexity and API smaller.

**Pull request closed without merging**
