### PR TITLE
#12044 hardcoded_sql_expressions bug

### LINKED ISSUE #12044: [FALSE NEGATIVE] "S608 Possible SQL injection"
Hello.
I'm very exited to migrate our codebase to ruff. However, while doing so I've noticed, that rule `S608` works different from the corresponding `B608`.
It only triggers if `SELECT` is on the same line.
So `SELECT * FROM {foo}.table` is an error and
```
SELECT *
FROM {foo}.table
```
Is not.

Kind regards, Mikhail

* B608
* S608
* sql injection

### PR DESCRIPTION
**Pull request by DataEnggNerd**
## Summary
This PR tried to fix #12044 raised for identifying all patterns which will be classified as prone to sql injections. 

## Test Plan
Created  `tests/test.py` will statements included in bug issue to check the implementation identifies all patterns. 

With the current change, only 2 scenarios are getting caught. Below is the log
```shell
cargo run -p ruff -- check --select S tests/test.py --no-cache
   Compiling ruff v0.6.2 (/Users/santhosh/Projects/personal/ruff/crates/ruff)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 4.87s
     Running `target/debug/ruff check --select S tests/test.py --no-cache`
tests/test.py:24:1: S608 Possible SQL injection vector through string-based query construction
   |
22 | foo = "foo"
23 |
24 | f"SELECT * FROM {foo}.table"
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ S608
   |

tests/test.py:27:1: S608 Possible SQL injection vector through string-based query construction
   |
27 | / f"""SELECT * FROM
28 | | {foo}.table
29 | | """
   | |___^ S608
30 |
31 |   f"""SELECT *
   |

Found 2 errors.
```

While when testing at online regex platforms, it is matching all the possible pattern in the test file. Below is the screenshot. 
Screenshot 2024-08-26 at 2 32 56 PM

### CODE REVIEW

**Comment by dhruvmanila** [comment]
Looking at this

**Comment by dhruvmanila** [comment]
I think there's more to it. The initial `\b` suggests that something like `\nSELECT` won't be matched because the "select" should be a complete word i.e., there should be some "gap" before the "select" word (newline doesn't count).

**Comment by dhruvmanila** [comment]
It makes sense to use word boundary because we don't want to match `deselect ...` here.

**Comment by DataEnggNerd** [comment]
Can I rewrite regex to match this rule?

**Comment by dhruvmanila** [comment]
I don't really have a good solution here, Rust regex engine doesn't support lookbehind other that could've been used probably.

**Comment by dhruvmanila** [comment]
> Or, if you're interested you can remove the regex completely and implement a custom parser ;)

Here's our `noqa` comment parser: https://github.com/astral-sh/ruff/blob/99df859e20e9527cbfea0b7f88d40c5f195dc57d/crates/ruff_linter/src/noqa.rs#L423-L584

But, it's totally fine otherwise and a regex solution will be good as well.

**Comment by DataEnggNerd** [comment]
@dhruvmanila Thanks for the suggestions. I will try implementing with Rust first. ✨

**Comment by dhruvmanila** [comment]
> @dhruvmanila Thanks for the suggestions. I will try implementing with Rust first. ✨

Feel free to ask any questions either on GitHub or Discord.

**Comment by DataEnggNerd** [comment]
> > @dhruvmanila Thanks for the suggestions. I will try implementing with Rust first. ✨
> 
> Feel free to ask any questions either on GitHub or Discord.

For sure! Will be starting by this weekend.

**Pull request closed without merging**
