### PR TITLE
Remove `import pytest` in `flake8-pytest-style` docs for consistency

### PR DESCRIPTION
**Pull request by harupy**
## Summary

#2646

### CODE REVIEW

**Comment by zanieb** [comment]
I think we've trended towards having the examples be executable (i.e. they include the necessary imports). Is there a reason you went with removal to these instead of addition to the others?

**Comment by harupy** [comment]
perhaps I should do the opposite.

**Comment by charliermarsh** [comment]
Yeah I'd probably vote to add to the other examples rather than remove.

**Comment by harupy** [comment]
Sounds good :) I'll close this PR and file a new one.

**Pull request closed without merging**
