### PR TITLE
(🎁) Add issue template search terms section

### LINKED ISSUE #10350: (🎁) Add "Search terms" to the new issue template
typescript has this super useful section in the issue template where you list searchable terms:

```yaml
- type: textarea
    id: search_terms
    attributes:
      label: '🔎 Search Terms'
      description: |
        What search terms did you use when trying to find an existing bug report?

        List them here so people in the future can find this one more easily.
      placeholder: |
        List of keywords you searched for before creating this issue. Write them down here so that others can find this bug more easily and help provide feedback.

        e.g. "function inference any", "jsx attribute spread", "move to file duplicate imports", "discriminated union inference", "ts2822"
    validations:
      required: true
```

### PR DESCRIPTION
**Pull request by KotlinIsland**
- resolves #10350

### CODE REVIEW

**Comment by zanieb** [comment]
Cool idea. I'd prefer not to add headings unless we're going to switch to an actual issue template.

**Comment by KotlinIsland** [comment]
Okay, how would you want this detail included, without the use of headings?

**Comment by zanieb** [comment]
I think so, just like a suggestion to include some search keywords at the bottom. I'm thinking a real issue form will make sense in the future, Charlie has just been opposed to it :)

**Comment by KotlinIsland** [comment]
I don't like issue forms much either. Want to take another look at this?

**Review by zanieb — APPROVED** [review]
Thanks! We'll give it a try.

**Pull request merged**
