### PR TITLE
[red-knot] Fix bug where union of two iterable types was not recognised as iterable

### LINKED ISSUE #13990: [red-knot] Union incorrectly reported as not iterable
Given:

```py

class TestIter:
    def __next__(self) -> str:
        return "abcd"


class Test:
    def __iter__(self) -> TestIter:
        return TestIter()


def bool_instance() -> bool:
    return True


flag = bool_instance()

if flag:
    a = "123"
else:
    a = Test()

x = "fallback"
for x in a:
    ...

reveal_type(x)
``` 

**Actual output**

```
ERROR /home/micha/astral/test/src/test.py:26:10: Object of type `Literal["123"] | Test` is not iterable
ERROR /home/micha/astral/test/src/test.py:29:1: Revealed type is `Literal["fallback"] | Unknown`
```

**Expected output**

```
ERROR /home/micha/astral/test/src/test.py:29:1: Revealed type is `Literal["fallback"] | str`
```

As part of this, we should also revisit if passing `self` here is correct because the first argument to `next` in this example isn't `Test` but `TestIter`

https://github.com/astral-sh/ruff/blob/1607d88c2253473a116155176effa4ab14eafcce/crates/red_knot_python_semantic/src/types.rs#L1115-L1121

### PR DESCRIPTION
**Pull request by AlexWaygood**
Fixes #13990. My favourite kind of bugfix: more accuracy for less code!

### CODE REVIEW

**Review by MichaReiser — COMMENTED** [review]
It would be nice to also have a test where one type is iterable and the other is not. E.g. iterator over `str | int`. 

This should work as expected today but I think the fix you pushed now would have regressed the diagnostic precision when our errors distinguish between a non-iterable and an iterator missing the `__next__` method.

**Comment by AlexWaygood** [comment]
> This should work as expected today

in fact, it does not... great catch!

**Comment by carljm** [comment]
> in fact, it does not

Should we capture this in an issue?

**Comment by AlexWaygood** [comment]
> > in fact, it does not
> 
> Should we capture this in an issue?

I am working on a fix. But if I do not succeed in putting up the fix, I will write up an issue.

**Comment by AlexWaygood** [comment]
> > > in fact, it does not
> > 
> > 
> > Should we capture this in an issue?
> 
> I am working on a fix. But if I do not succeed in putting up the fix, I will write up an issue.

I did not succeed in putting up the fix! Here is the issue instead: https://github.com/astral-sh/ruff/issues/14012

**Pull request merged**
