### PR TITLE
Consider alternate split points for line-too-long exemptions

### PR DESCRIPTION
**Pull request by charliermarsh**
Looking for ecosystem results here to make a call.

See: https://github.com/astral-sh/ruff/issues/8383.

### CODE REVIEW

**Comment by charliermarsh** [comment]
I don't love what I'm seeing from the ecosystem checks. Some of these changes are "good"... I could use a second pair of eyes.

**Comment by T-256** [comment]
> I don't love what I'm seeing from the ecosystem checks

Overall good changes. which types you didn't like?

**Comment by MichaReiser** [comment]
> I don't love what I'm seeing from the ecosystem checks. Some of these changes are "good"... I could use a second pair of eyes.

Could you share a few examples for the cases you dislike?

**Comment by charliermarsh** [comment]
- https://github.com/commaai/openpilot/blob/e687be939e7cf67c4a75b87320ab058941d4316f/system/sensord/pigeond.py#L172
- https://github.com/pandas-dev/pandas/blob/f7c73a5f1aaf0724598e60c0cc5732604ec842a8/pandas/tests/util/test_hashing.py#L359
- https://github.com/pypa/pip/blob/a15dd75d98884c94a77d349b800c7c755d8c34e4/src/pip/_internal/models/wheel.py#L17
- https://github.com/aws/aws-sam-cli/blob/870c547f210b9dbd93abf75e7a0a1ec9b292c50b/tests/integration/init/schemas/schemas_test_data_setup.py#L156

**Comment by MichaReiser** [comment]
Yeah, this doesn't look ideal. I like the examples where there's some python code, e.g. a call that passes a long string as an argument. But splitting some of the strings would lead to worse formatting. 

Could we rely on the lexed tokens of the line to identify if it is a single string literal that can't be split or if there are any other Python tokens that are valid split points?

**Comment by MichaReiser** [comment]
I'll close this PR because there hasn't been any activity in a while. Feel free to reopen if you plan to continue working on this.

**Pull request closed without merging**
