### PR TITLE
[pep8-naming] Also check invalid-module-name if file is not in package (N999)

### PR DESCRIPTION
**Pull request by AlexElvers**
## Summary

**Old behavior:**
If `package` is `None` in `invalid_module_name`, checking the module name is skipped. This is different from the https://pypi.org/project/flake8-module-name/ behavior, where module names are checked for all Python files (independent of being in a package).

**New behavior:**
Also check for invalid module names for files that are not in a package. This ensures that all `.py` files can be imported.

## Comparison of ruff and flake8 outputs

```
$ tree
.
├── a-a.py
├── b
│   └── b-b.py
└── c
    ├── __init__.py
    └── c-c.py

3 directories, 4 files

$ flake8 --isolated --select N999 *
a-a.py:0:1: N999 filename should be all lower case
b/b-b.py:0:1: N999 filename should be all lower case
c/c-c.py:0:1: N999 filename should be all lower case

# before change
$ ruff check --isolated --select N999 *
c/c-c.py:1:1: N999 Invalid module name: 'c-c'
Found 1 error.

# after change
$ cargo run -p ruff -- check --isolated --select N999 --no-cache *
...
a-a.py:1:1: N999 Invalid module name: 'a-a'
b/b-b.py:1:1: N999 Invalid module name: 'b-b'
c/c-c.py:1:1: N999 Invalid module name: 'c-c'
Found 3 errors.
```

## Test Plan

New test case in `crates/ruff_linter/src/rules/pep8_naming/mod.rs` and successful execution of `cargo nextest run`.

### CODE REVIEW

**Comment by MichaReiser** [comment]
This looks reasonable to me. I do think that we should gate the change behind preview mode. A minor release is required when

> The scope of a stable rule is significantly increased

Whether this is a *significant* increase is debatable. I'm leaning towards being safe. @AlexWaygood what do you think?

**Review by MichaReiser — APPROVED** [review]

**Comment by charliermarsh** [comment]
I'm torn on this, since it's not that uncommon to use invalid module names for standalone scripts. We even do it in uv.

**Comment by AlexWaygood** [comment]
> I'm torn on this, since it's not that uncommon to use invalid module names for standalone scripts. We even do it in uv.

Yeah. I'm -1 on this being part of N999. We already have https://github.com/astral-sh/ruff/issues/12475 complaining (reasonably, in my view) that this rule is too broad. I don't think we should broaden it further.

Possibly this could be added as a separate rule. But it would be a very opinionated rule, in my opinion. As @charliermarsh says, it's pretty common for single-file scripts to have names with hyphens in them or whatever. And that's fine, if you never intend to import them from other modules.

**Comment by MichaReiser** [comment]
From reading the above, it seems we have no support for this rule change. 

Thanks @AlexElvers for putting the time into this and I'm sorry this has not a more positive outcome.

**Comment by AlexElvers** [comment]
Thanks for the debate! I'm now hoping for a rule split as suggested in #12475 too. :slightly_smiling_face:

**Pull request closed without merging**
