### PR TITLE
Commit the lockfile for `fuzz` crate

### PR DESCRIPTION
**Pull request by dhruvmanila**
## Summary

This PR adds the `Cargo.lock` file back to the `fuzz` crate.

I'm not exactly sure why this was removed in https://github.com/astral-sh/ruff/pull/5008 but I suspect that it causes problems in upgrading the dependencies (https://github.com/astral-sh/ruff/pull/12558).

I generated the lockfile using:
```
cargo generate-lockfile --manifest-path fuzz/Cargo.toml
```

Another way which produces the same lockfile:
```
cargo update --manifest-path fuzz/Cargo.toml
```

### CODE REVIEW

**Comment by MichaReiser** [comment]
Hmm not sure. I could see that re-adding the lock file could be annoying because we then have to update two lock files whenever we change any dependency (once in Ruff, and once in the fuzzer). Maybe we should just tweak renovate to not update the fuzzer project?

**Comment by dhruvmanila** [comment]
> I could see that re-adding the lock file could be annoying because we then have to update two lock files whenever we change any dependency (once in Ruff, and once in the fuzzer).

Wouldn't Renovate update both of them which is what it's doing in https://github.com/astral-sh/ruff/pull/12558? Or, is your concern related to local development?

**Comment by MichaReiser** [comment]
My concern is about local development and I'm not sure how important a lockfile is for `fuzz`, because we don't ship it.

**Comment by dhruvmanila** [comment]
> My concern is about local development and I'm not sure how important a lockfile is for `fuzz`, because we don't ship it.

Yeah, makes sense.

**Pull request closed without merging**
