### PR TITLE
Add `Issue Links` section to PR template

### PR DESCRIPTION
**Pull request by evanrittenhouse**

### CODE REVIEW

**Comment by evanrittenhouse** [comment]
Force-pushed to rerun checks now that the `mkdocs` SSH issue is fixed. Ready for review.

**Comment by evanrittenhouse** [comment]
@charliermarsh Just wanted to bump this, gave you edit rights in case you want to modify it

**Comment by charliermarsh** [comment]
@evanrittenhouse - Appreciate the PR but I think I'd rather avoid adding another section for this. We do have a note at the top suggesting that users include links to relevant issues, and in general folks seem to do a good job of this.

We could either leave it as-is, or change `Does this pull request include references to any relevant issues?` to `Does this pull request include references to any relevant issues? (E.g., "Closes <Issue>.")`.

**Comment by charliermarsh** [comment]
Gonna close based on the above, but let me know if you feel differently.

**Comment by evanrittenhouse** [comment]
Nah makes sense. I was gonna close it today but got pulled into something at work

**Pull request closed without merging**
