### PR TITLE
Move `Ranged` into `ruff_text_size`

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

The motivation here is that this enables us to implement `Ranged` in crates that don't depend on `ruff_python_ast`.

Largely a mechanical refactor with a lot of regex, Clippy help, and manual fixups.

## Test Plan

`cargo test`

### CODE REVIEW

**Comment by charliermarsh** [comment]
Trying to fix these failures but my `git push` is hanging 😅

**Comment by MichaReiser** [comment]
Oh god... I hope this is not clashing with my refactor xD

**Review by MichaReiser — APPROVED** [review]

**Comment by charliermarsh** [comment]
Oh god. Do you want me to do the rebase?

**Comment by MichaReiser** [comment]
> Oh god. Do you want me to do the rebase?

Go ahead, we should be fine for most files :)

**Pull request merged**
