### PR TITLE
Use the new f-string tokens in string formatting

### PR DESCRIPTION
**Pull request by dhruvmanila**
## Summary

This PR updates the string formatter to account for the new f-string tokens.

The formatter uses the full lexer to handle comments around implicitly concatenated strings. The reason it uses the lexer is because the AST merges them into a single node so the boundaries aren't preserved.

For f-strings, it creates some complexity now that it isn't represented as a `String` token. A single f-string will atleast emit 3 tokens (`FStringStart`, `FStringMiddle`, `FStringEnd`) and if it contains expressions, then it'll emit the respective tokens for them. In our case, we're currently only interested in the outermost f-string range for which I've introduced a new `FStringRangeBuilder` which keeps builds the outermost f-string range by considering the start and end tokens and the nesting level.

Note that this doesn't support in any way nested f-strings which is out of scope for this PR. This means that if there are nested f-strings, especially the ones using the same quote, the formatter will escape the inner quotes:

```python
f"hello world {
    x
        +
            f\"nested {y}\"
}"
```

## Test plan

```
cargo test --package ruff_python_formatter
```

### CODE REVIEW

**Comment by dhruvmanila** [comment]
Hmm, I've rebased the stack on the latest main so not sure why does `mdformat` wants to format those markdown files.

**Comment by dhruvmanila** [comment]
(Looking into the formatter ecosystem failures)

**Comment by charliermarsh** [comment]
Hm, I wonder if this is related to https://github.com/astral-sh/ruff/pull/7538?

**Comment by dhruvmanila** [comment]
> Hm, I wonder if this is related to #7538?

Are you referring to the ecosystem checks or pre-commit (`mdformat`)?

**Comment by charliermarsh** [comment]
The `mdformat` change. Those files should be in the `.gitignore`, right?

**Comment by dhruvmanila** [comment]
> The `mdformat` change. Those files should be in the `.gitignore`, right?

Oh, my bad. A few files got added when I was exploring `mkdocs-material` 😅

**Comment by dhruvmanila** [comment]
Current dependencies on/for this PR:
* dhruv/pep-701
  * **PR #7586** <a href="https://app.graphite.dev/github/pr/astral-sh/ruff/7586" target="_blank">Graphite</a>  👈
    * **PR #7588** <a href="https://app.graphite.dev/github/pr/astral-sh/ruff/7588" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/astral-sh/ruff/7586?utm_source=stack-comment).

**Review by MichaReiser — APPROVED** [review]

**Pull request merged**
