### PR TITLE
[`refurb`] - add `bool-literal-compare` with fix (`FURB149`)

### PR DESCRIPTION
**Pull request by diceroll123**
## Summary

Add [`bool-literal-compare` (`FURB149`)](https://github.com/dosisod/refurb/blob/master/refurb/checks/readability/no_is_bool_compare.py) with fix

See: #1348 

## Test Plan

`cargo test`

### CODE REVIEW

**Comment by tjkuson** [comment]
What overlap does this have with [`true-false-comparison` (`E712`)](https://docs.astral.sh/ruff/rules/true-false-comparison/)?

**Comment by diceroll123** [comment]
Hrm, in theory, FURB149 could fix it before E712 fixes it, or, E712 fixes it and then FURB149 fixes it afterward.

**Review by charliermarsh — COMMENTED** [review]
This looks pretty similar to [`true-false-comparison`](https://docs.astral.sh/ruff/rules/true-false-comparison/), do you mind comparing the two rules?

**Comment by charliermarsh** [comment]
Ugh, sorry, I missed @tjkuson comment 🤦

**Comment by charliermarsh** [comment]
But do you know if the rules catch the same cases, @diceroll123?

**Comment by diceroll123** [comment]
Made an update; I fixed an edge case or two, and narrowed it to disallow chained comparisons while doing the testing below, and after some consideration I've also made the fixes both set to unsafe.

Here's a comparison of both E712 and FURB149 autofixes ran on the same file:

Running E712 on the E712.py text fixture (with fixes) gives this:
image

---

Running FURB149 on the same file with fixes:

image

**Comment by MichaReiser** [comment]
Thanks @diceroll123  for working on this PR and writing up the difference to `true-false-comparision`. 

I understand that this rull and `bool-literal-compare` identify the same code smell but provide different fixes. We should only have one rule, or the experience for users is confusing (what fix am I supposed to use and why?) I see two solutions, but this requires more design before opening a follow-up PR:

* An option is to extend `bool-literal-compare` to specify the preferred fix. 
* Wait until Ruff has access to types and use the type information to decide if the safe fix is to fix to `x is True` or `x`. 

I'm happy to check in with the team to see what they think of adding an option to `true-false-comparision` to direct the fix but I'll close this PR because Ruff should only have a single rule per code-smell.

**Pull request closed without merging**
