### PR TITLE
Fix F821 regression for classes marked as runtime-required

### LINKED ISSUE #10451: F821 false-positive for SQLAlchemy mappings with not yet declared classes
The described behavior happens since 0.3.3. It might be related to https://github.com/astral-sh/ruff/issues/10340

It is triggered throughout my SQLAlchemy models in cases where a model is not defined yet while used in  a type annotation

Minimal repro:

```python
from __future__ import annotations

from sqlalchemy.orm import DeclarativeBase, Mapped


class Base(DeclarativeBase):
    some_mapping: Mapped[list[Bar]] | None = None # F821 Undefined name `Bar`
    simplified: list[Bar] | None = None # F821 Undefined name `Bar`


class Bar:
    pass
```

I can only trigger the error when inheriting from `DeclarativeBase`. Without this inheritance or when inheriting from another class, things are fine.

### PR DESCRIPTION
**Pull request by AlexWaygood**
Fixes #10451. This is basically a revert of 704fefc, but includes a more principled fix for the issue that that PR was trying to fix (#10362)

### CODE REVIEW

**Comment by charliermarsh** [comment]
I think this is not quite right but I haven't dug into why. It seems off to me that we have to set `runtime_annotation` in those various places here.

**Comment by AlexWaygood** [comment]
Yeah, the ecosystem results indicate that this definitely is not quite right just yet :/

**Comment by charliermarsh** [comment]
Let's start with a revert and revisit the fix itself.

**Comment by AlexWaygood** [comment]
Sure, I'll do a revert PR now 👍

**Comment by AlexWaygood** [comment]
#10513 to revert.

**Comment by AlexWaygood** [comment]
I'm still looking at this locally, but closing the PR for now

**Pull request closed without merging**
