### PR TITLE
[`DTZ`] Improve docs for `call-datetime-without-tzinfo` (`DTZ005`)

### LINKED ISSUE #10251: DTZ005 false postitive for `tz=None`
```python
import datetime

datetime.datetime.now(tz=None) 
# The use of `datetime.datetime.now()` without `tz` argument is not allowed Ruff DTZ005
```

ruff 0.1.9

### PR DESCRIPTION
**Pull request by cclauss**
Fixes #10251
* #10251

### CODE REVIEW

**Review by MichaReiser — APPROVED** [review]

**Comment by AlexWaygood** [comment]
Hmm, I'm not sure about just adding a paragraph at the bottom. Possibly you could argue that the first sentence of the documentation for this rule is wrong:

> Checks for usage of `datetime.datetime.now()` without a `tz` argument.

In reality, it does more than that, since it also emits an error if you explicitly pass `tz=None`. Probably it would be more accurate to say:

> Checks for usage of `datetime.datetime.now()` that do not specify a timezone.

Then we could explain in the body of the rule's documentation why `tz=None` is, from the perspective of this rule, the same antipattern as failing to pass a `tz=` argument at all.

**Review by AlexWaygood — COMMENTED** [review]
Looks good! Could you also change the error message? It's currently

> "The use of `datetime.datetime.now()` without `tz` argument is not allowed"

It should be

> "Using `datetime.datetime.now()` without specifying a timezone is not allowed"

**Review by AlexWaygood — APPROVED** [review]
Thanks!

**Comment by cclauss** [comment]
We have lost this notion from the original commit...
> For a timezone-aware datetime for the machine's timezone, use:
> `datetime.datetime.now(tz=datetime.timezone.utc).astimezone()`

**Comment by AlexWaygood** [comment]
> We have lost this helpful hint from the original commit...
> 
> > For a timezone-aware datetime for the machine's timezone, use:
> > `datetime.datetime.now(tz=datetime.timezone.utc).astimezone()`

Right. I think that could be worked into the docs somewhere; I agree that it's useful.

I'm also wondering if we could tailor the error message to the specific thing that the user is doing wrong. Something like this?

```diff
--- a/crates/ruff_linter/src/rules/flake8_datetimez/rules/call_datetime_now_without_tzinfo.rs
+++ b/crates/ruff_linter/src/rules/flake8_datetimez/rules/call_datetime_now_without_tzinfo.rs
@@ -1,3 +1,5 @@
+use std::fmt;
+
 use ruff_diagnostics::{Diagnostic, Violation};
 use ruff_macros::{derive_message_formats, violation};
 
@@ -6,7 +8,6 @@ use ruff_python_semantic::Modules;
 use ruff_text_size::Ranged;
 
 use crate::checkers::ast::Checker;
-use crate::rules::flake8_datetimez::rules::helpers::has_non_none_keyword;
 
 use super::helpers;
 
@@ -48,12 +49,28 @@ use super::helpers;
 /// ## References
 /// - [Python documentation: Aware and Naive Objects](https://docs.python.org/3/library/datetime.html#aware-and-naive-objects)
 #[violation]
-pub struct CallDatetimeNowWithoutTzinfo;
+pub struct CallDatetimeNowWithoutTzinfo(DatetimeNowAntipattern);
 
 impl Violation for CallDatetimeNowWithoutTzinfo {
     #[derive_message_formats]
     fn message(&self) -> String {
-        format!("Using `datetime.datetime.now()` without specifying a timezone is not allowed")
+        let CallDatetimeNowWithoutTzinfo(antipattern) = self;
+        format!("{antipattern} is not allowed")
+    }
+}
+
+#[derive(Debug, Clone, Copy, Eq, PartialEq)]
+enum DatetimeNowAntipattern {
+    NoTzArgumentPassed,
+    NonePassedToTzArgument,
+}
+
+impl fmt::Display for DatetimeNowAntipattern {
+    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
+        f.write_str(match self {
+            Self::NoTzArgumentPassed => "Using `datetime.datetime.now()` without a `tz=` argument",
+            Self::NonePassedToTzArgument => "Passing `tz=None` to `datetime.datetime.now()`",
+        })
     }
 }
 
@@ -78,9 +95,10 @@ pub(crate) fn call_datetime_now_without_tzinfo(checker: &mut Checker, call: &ast
 
     // no args / no args unqualified
     if call.arguments.args.is_empty() && call.arguments.keywords.is_empty() {
-        checker
-            .diagnostics
-            .push(Diagnostic::new(CallDatetimeNowWithoutTzinfo, call.range()));
+        checker.diagnostics.push(Diagnostic::new(
+            CallDatetimeNowWithoutTzinfo(DatetimeNowAntipattern::NoTzArgumentPassed),
+            call.range(),
+        ));
         return;
     }
 
@@ -91,16 +109,24 @@ pub(crate) fn call_datetime_now_without_tzinfo(checker: &mut Checker, call: &ast
         .first()
         .is_some_and(Expr::is_none_literal_expr)
     {
-        checker
-            .diagnostics
-            .push(Diagnostic::new(CallDatetimeNowWithoutTzinfo, call.range()));
+        checker.diagnostics.push(Diagnostic::new(
+            CallDatetimeNowWithoutTzinfo(DatetimeNowAntipattern::NonePassedToTzArgument),
+            call.range(),
+        ));
         return;
     }
 
-    // wrong keywords / none keyword
-    if !call.arguments.keywords.is_empty() && !has_non_none_keyword(&call.arguments, "tz") {
-        checker
-            .diagnostics
-            .push(Diagnostic::new(CallDatetimeNowWithoutTzinfo, call.range()));
+    if let Some(keyword_argument) = call.arguments.find_keyword("tz") {
+        if keyword_argument.value.is_none_literal_expr() {
+            checker.diagnostics.push(Diagnostic::new(
+                CallDatetimeNowWithoutTzinfo(DatetimeNowAntipattern::NonePassedToTzArgument),
+                call.range(),
+            ));
+        }
+    } else {
+        checker.diagnostics.push(Diagnostic::new(
+            CallDatetimeNowWithoutTzinfo(DatetimeNowAntipattern::NoTzArgumentPassed),
+            call.range(),
+        ));
     }
 }
diff --git a/crates/ruff_linter/src/rules/flake8_datetimez/snapshots/ruff_linter__rules__flake8_datetimez__tests__DTZ005_DTZ005.py.snap b/crates/ruff_linter/src/rules/flake8_datetimez/snapshots/ruff_linter__rules__flake8_datetimez__tests__DTZ005_DTZ005.py.snap
index 2f24cc4dc..d79264aad 100644
--- a/crates/ruff_linter/src/rules/flake8_datetimez/snapshots/ruff_linter__rules__flake8_datetimez__tests__DTZ005_DTZ005.py.snap
+++ b/crates/ruff_linter/src/rules/flake8_datetimez/snapshots/ruff_linter__rules__flake8_datetimez__tests__DTZ005_DTZ005.py.snap
@@ -1,7 +1,7 @@
 ---
 source: crates/ruff_linter/src/rules/flake8_datetimez/mod.rs
 ---
-DTZ005.py:4:1: DTZ005 Using `datetime.datetime.now()` without specifying a timezone is not allowed
+DTZ005.py:4:1: DTZ005 Using `datetime.datetime.now()` without a `tz=` argument is not allowed
   |
 3 | # no args
 4 | datetime.datetime.now()
@@ -10,7 +10,7 @@ DTZ005.py:4:1: DTZ005 Using `datetime.datetime.now()` without specifying a timez
 6 | # wrong keywords
   |
 
-DTZ005.py:7:1: DTZ005 Using `datetime.datetime.now()` without specifying a timezone is not allowed
+DTZ005.py:7:1: DTZ005 Using `datetime.datetime.now()` without a `tz=` argument is not allowed
   |
 6 | # wrong keywords
 7 | datetime.datetime.now(bad=datetime.timezone.utc)
@@ -19,7 +19,7 @@ DTZ005.py:7:1: DTZ005 Using `datetime.datetime.now()` without specifying a timez
 9 | # none args
   |
 
-DTZ005.py:10:1: DTZ005 Using `datetime.datetime.now()` without specifying a timezone is not allowed
+DTZ005.py:10:1: DTZ005 Passing `tz=None` to `datetime.datetime.now()` is not allowed
    |
  9 | # none args
 10 | datetime.datetime.now(None)
@@ -28,7 +28,7 @@ DTZ005.py:10:1: DTZ005 Using `datetime.datetime.now()` without specifying a time
 12 | # none keywords
    |
 
-DTZ005.py:13:1: DTZ005 Using `datetime.datetime.now()` without specifying a timezone is not allowed
+DTZ005.py:13:1: DTZ005 Passing `tz=None` to `datetime.datetime.now()` is not allowed
    |
 12 | # none keywords
 13 | datetime.datetime.now(tz=None)
@@ -37,7 +37,7 @@ DTZ005.py:13:1: DTZ005 Using `datetime.datetime.now()` without specifying a time
 15 | from datetime import datetime
    |
 
-DTZ005.py:18:1: DTZ005 Using `datetime.datetime.now()` without specifying a timezone is not allowed
+DTZ005.py:18:1: DTZ005 Using `datetime.datetime.now()` without a `tz=` argument is not allowed
    |
 17 | # no args unqualified
 18 | datetime.now()
```

(I'm happy to push that straight to your branch if you like it, since I've already tried it out locally!)

**Comment by charliermarsh** [comment]
I'm gonna defer to Alex on the actual copy, but I'll note that similar changes may need to be applied to the other DTZ rules which enforce the ~same thing.

**Pull request closed without merging**
