### PR TITLE
[`pylint`] Implement `potential-index-error` (`PLE0643`)

### PR DESCRIPTION
**Pull request by diceroll123**
## Summary

add `potential-index-error` rule (`PLE0643`)

See: #970 

## Test Plan

`cargo test`

### CODE REVIEW

**Comment by Skylion007** [comment]
It's quite common to deal with int64 array indices in machine learning and big data applications so I would recommend allow 64bit indices. Seems like the speed difference wouldn't be worth improperly handling these edge cases?

**Comment by diceroll123** [comment]
I'd love to see a way for arbitrary integer comparisons here, but I don't think we'll be able to do that without adding dependencies. I'd love to be proven wrong, but I'd also argue that 64 bits is beyond plenty in this scenario.

**Review by charliermarsh — APPROVED** [review]
Thanks!

**Comment by diceroll123** [comment]
Great tweaks!

**Pull request merged**
