### PR TITLE
Add delay between updating a file

### PR DESCRIPTION
**Pull request by MichaReiser**
## Summary

This PR should fix some flaky integration tests in file watching. 

The test became flaky with https://github.com/astral-sh/ruff/pull/12566 because we now only write the last
modified timestamp if it has changed. However, the last modified timestamp might remain unchanged
if the write operations happen only a few ns seconds a part and the duration is larger than the system's precision of the last modified time.

## Test Plan

I can't reproduce the test failures localy, which makes it difficult to verify that the flakiness is fixed.
We can increment the delay if necessary.

### CODE REVIEW

**Review by AlexWaygood — COMMENTED** [review]
In general I share @carljm's concerns from https://github.com/astral-sh/ruff/pull/12382#discussion_r1685218148 about using hardcoded sleeps in tests. It's usually pretty hard to get them right and avoid flakiness.

What if we did something like this?

```rs
use std::time::SystemTime;

fn next_io_tick() {
    let start = SystemTime::now();
    std::thread::sleep(Duration::from_nanos(100));
    // Continue sleeping until the system clock
    // recognises that the time is later than it was
    // when we started this function...
    loop {
        let Ok(elapsed) = SystemTime::now().duration_since(start) else {
            std::thread::sleep(Duration::from_nanos(50));
            continue;
        }
        if elapsed.as_nanos() == 0 {
            std::thread::sleep(Duration::from_nanos(50));
            continue;
        }
        return;
    }
}

**Comment by MichaReiser** [comment]
I also share the concern about sleeping in tests but I'm not sure if it warrant's the extra complexity. The only "proper" solution would be to create a file and write to it in a spin loop until the last modified time changes. Because only this approach would account for different precisions between different file systems. 

Regarding the warning in the documentation. This is a test and not production code. We can change the code if Rust decides to change some precision.

**Comment by MichaReiser** [comment]
I don't mind a proper solution but I want to avoid "wasting" time on it if a much simpler solution works reasonably well. We could even bump the timeout to 100ms or 1s without regressing the CI time significantly.

**Comment by AlexWaygood** [comment]
Slowing down CI isn't my primary concern here; Ruff's CI speed is ~okay, and I agree that a tiny sleep here isn't going to make a material difference considering the time it takes to build Ruff in CI. My primary concern is that adding the sleep won't get rid of the flakes completely, even if it's a large sleep that "should" be guaranteed to be longer than the system clock precision. That's been my experience working on other projects such as CPython.

Maybe adding this sleep means that the test only flakes 1 in 500 times instead of 1 in 10 times. That's okay when you only have 1 test like this, but it ends up creating a reasonable amount of test flakiness in CI if we have 100 tests like this in a few weeks.

I'm okay with this landing if you're confident it fixes the flakes, but I'd _prefer_ a more principled solution, especially if we expect to use the `next_io_tick()` function more widely in our tests going forward.

**Comment by carljm** [comment]
I don't like sleeping in tests, but it's probably unavoidable in this case, and I suspect the most important factor here is that we shouldn't ever have hundreds or thousands of tests relying on this; most of our tests should not be integration tests at a level where we are testing file-watching responsiveness. Plus, as long as we _have_ the abstraction of the `next_io_tick` function in place, we can always change its implementation as needed in the future without needing to change a bunch of tests.

IMO the more likely issue that will cause us to have more flaky tests in future is just the fact that it's required to remember to call this manually in the test, rather than having it built-in to a file-writing utility used by all the file-watching tests.

**Review by carljm — APPROVED** [review]

**Review by AlexWaygood — APPROVED** [review]

**Comment by AlexWaygood** [comment]
The test still appears to be flaky: https://github.com/astral-sh/ruff/actions/runs/10166452757/job/28116662757?pr=12582

**Pull request merged**
