### PR TITLE
Add check for is comparison with mutable initialisers to rule F632

### PR DESCRIPTION
**Pull request by jesse1412**
## Summary

Adds an extra check to F632 to check for any `is` comparisons to a mutable initialisers.
Implements #8589 .

Example:
```Python
named_var = {}
if named_var is {}:  # F632 (fix)
    pass
```
The if condition will always evaluate to False because it checks on identity and it's impossible to take the same identity as a hard coded list/set/dict initializer.

Multiple test cases were added to ensure the rule works + doesn't flag false positives + the fix works correctly.

### CODE REVIEW

**Comment by vinhocent** [comment]
Just wondering - what was the original reasoning for not using a `match` statement in `is_constant()` @charliermarsh ?

**Comment by zanieb** [comment]
We should probably gate this change to only apply when preview mode is enabled per [the versioning policy](https://docs.astral.sh/ruff/versioning/#version-changes)

> The scope of a stable rule is significantly increased

**Comment by zanieb** [comment]
Thanks for contributing :) the rest of the implementation looks good to me. I don't have the answer to your question though.

**Comment by jesse1412** [comment]
I thiiink I've added the preview flag. And thanks for the encouraging words!

**Review by charliermarsh — APPROVED** [review]
Great, thank you!

**Pull request merged**
