### PR TITLE
[`pylint`] Implement `if-stmt-min-max` (`PLR1730`, `PLR1731`)

### PR DESCRIPTION
**Pull request by tibor-reiss**
Add rule [consider-using-min-builtin (R1730)](https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/consider-using-min-builtin.html) and [consider-using-max-builtin (R1731)](https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/consider-using-max-builtin.html)

See https://github.com/astral-sh/ruff/issues/970 for rules

Test Plan: `cargo test`

### CODE REVIEW

**Comment by tibor-reiss** [comment]
Hi @charliermarsh, some questions regarding this PR:
- min and max are 2 separate rules in pylint, so I implemented as such with their respective codes - looking at other similar rules this seems to be the standard for now. However, there is minimal difference between the 2 functions min_instead_of_if and max_instead_of_if. So I wonder if it would not be better to merge these 2 rules into one?
- is there some simple general way of matching the "value" part in literals, i.e. ignoring the range field? E.g. I could not find any example so far for a simple comparison of two python constants.

**Comment by sbrugman** [comment]
Another related rule:
https://github.com/dosisod/refurb/blob/master/docs/checks.md#furb136-use-min-max

#1348

**Comment by tibor-reiss** [comment]
@sbrugman While they look indeed similar, the implementation is quite different: FURB136 is for if expressions (in ruff it is ExprIfExp which is an Expr enum), whereas PLR1730 operates on if statements (in ruff it is StmtIf which is a Stmt enum).

**Comment by sbrugman** [comment]
I linked it as reference for the first point: here it is implemented as a single rule. Consistency with the upstream (mapping existing rules) takes precedence over internal consistency (merging rules that are minimally different) I suppose, so just for reference.

**Comment by tibor-reiss** [comment]
@sbrugman Thanks for clarifying, I misunderstood your original comment. I added now a commit which merges the 2 rules - I personally also prefer this over the duplication. @charliermarsh to decide if this is acceptable - i.e. dropping PLR1731 and just using PLR1730 for both min and max.

**Comment by sbrugman** [comment]
Sorry for the confusion, but I intended to say that the linked rule merged them at one, but since that pylint treats them as two for now the project prefers to match pylint (i.e. two rules). Anyway, indeed let the team decide on that

**Comment by tibor-reiss** [comment]
@sbrugman From the linked reference I found out that there is ComparableExpr - code looks a lot cleaner now. So thanks a lot for taking a look!

**Comment by MichaReiser** [comment]
The rule itself fits into ruff. It is similar to [if-expr-min-max](https://docs.astral.sh/ruff/rules/if-expr-min-max/) but we have other rules that capture the same problem but differ in the syntax. 

Onet thing that needs to be decided if this should be a single rule or if it's better to have two rules (to match py lint)

**Comment by charliermarsh** [comment]
I'm comfortable with a single rule here. Just seems unlikely that anyone would enable one but not the other, and it better aligns with `if-expr-min-max`. I'll rename and merge.

**Review by charliermarsh — APPROVED** [review]

**Pull request merged**
