### PR TITLE
feat: add rule which detects LDAP injections

### PR DESCRIPTION
**Pull request by spaceone**
Issue #2730

the snapshots represent the target test result → there are some leftover TODOs.

TODO: need decision for the rule number/code

feedback or help appreciated

### CODE REVIEW

**Comment by charliermarsh** [comment]
Sorry, the reason I haven't gotten around to reviewing this (shame 🙈) is that I don't feel super qualified to comment on whether it's a useful rule, whether it'll have high accuracy and precision, and so on. I'd love to see this implemented in Bandit as a reference to guide us... But, from the Bandit issue, it seems like there's no clear timeline on when that would happen.

**Comment by spaceone** [comment]
bandit won't ever do it probably. The future is also `ruff`. I won't re-implement the same in Python for bandit.

**Comment by spaceone** [comment]
> Hey @spaceone — I'm going through some old pull requests and noticed that we didn't reply here. Sorry about that! We don't feel that we have the expertise to review or maintain this. Would you be help able to find a reviewer that's an expert in the domain?

hmm, I could ask people from my own company. And I asked here: https://github.com/astral-sh/ruff/pull/2811#issuecomment-1644006896

**Comment by zanieb** [comment]
Hm it looks like they'd go a different route https://github.com/PyCQA/bandit/issues/309#issuecomment-1649114812

**Pull request closed without merging**
