### PR TITLE
Add openSUSE Tumbleweed into install doc

### PR DESCRIPTION
**Pull request by mimi1vx**

### CODE REVIEW

**Review by zanieb — COMMENTED** [review]
I'm a little worried this is too specific, I don't think we should necessarily enumerate every Linux distribution. Curious to hear what others think though.

**Comment by MichaReiser** [comment]
> I'm a little worried this is too specific, I don't think we should necessarily enumerate every Linux distribution. Curious to hear what others think though.

We already list other Linux distributions like Arch and Alpine linux. Is your concern about us doing this in general or is it new because the list starts to become rather long?

**Comment by mimi1vx** [comment]
plus for openSUSE there is difference because is packaged as standard python package --> so name is python3-ruff

**Comment by konstin** [comment]
If the linux list becomes too long we could switch to a markdown table for all linux distros

**Comment by charliermarsh** [comment]
Sounds good. We can merge for now and revisit if it becomes a problem...

**Pull request merged**
