### PR TITLE
[`pylint`] Implement `non-ascii-name` (`C2401`)

### PR DESCRIPTION
**Pull request by LaBatata101**
## Summary
Checks for the use of non-ASCII unicode character in identifiers.

Some non-ASCII unicode characters looks identical to ASCII characters, that may cause confusion and hard to catch bugs in your code.

For example, the uppercase version of the Latin `b`, Greek `β` (Beta), and Cyrillic `в` (Ve) often look identical: `B`, `Β` and `В`, respectively.

This allows identifiers to look the same for you, but not for Python. For example, the following identifiers are all distinct:
   - `scope` (Latin, ASCII-only)
   - `scоpe` (with a Cyrillic `о`)
   - `scοpe` (with a Greek `ο`)

Reference: [PEP-0672](https://peps.python.org/pep-0672/#confusing-features)

ref: #970 

## Test Plan

Snapshots and manual runs of `pylint`

### CODE REVIEW

**Comment by zanieb** [comment]
Are we concerned about the overlap between this and [`RUF001`](https://beta.ruff.rs/docs/rules/ambiguous-unicode-character-string/)? cc @charliermarsh

**Comment by LaBatata101** [comment]
> Are we concerned about the overlap between this and [`RUF001`](https://beta.ruff.rs/docs/rules/ambiguous-unicode-character-string/)? cc @charliermarsh

It doesn't seem to be an overlap between `C2401` and `RUF001`. `RUF001` only checks for ambiguous Unicode characters in strings and comments while `C2401` checks any **non-ASCII** character in `ClassDef`, `FunctionDef`, `Assign`, `AugAssign`, `AnnAssign` and `Global` statements. 

Running `RUF001` in `crates/ruff/resources/test/fixtures/pylint/non_ascii_name.py` doesn't yield any diagnostic reports.

**Comment by zanieb** [comment]
Thanks for investigating!

**Comment by charliermarsh** [comment]
Ugh, I'm really sorry @LaBatata101, this got re-PR'd as https://github.com/astral-sh/ruff/pull/8038 and I just reviewed and merged that version. It's entirely my fault for (1) not reviewing this earlier, and then (2) missing that this PR was already up. I sincerely apologize.

**Pull request closed without merging**
