### PR TITLE
[`ruff`] Implement compound comparison rule (`RUF029`)

### LINKED ISSUE #8964: Rule suggestion: lint against the use of `in` with compound comparisons
The use of `in` with compound comparisons often leads to unintended/surprising behaviour.

```python
False == False in [False]  # True
```

A solution would be to use parentheses.

```python
(False == False) in [False]  # False
False == (False in [False])  # False
```

Similar to #8721, but the AST produced by `False or False and False` is quite different, so might be a different rule.

### PR DESCRIPTION
**Pull request by tjkuson**
## Summary

Implements `non-transitive-compound-comparison` (`RUF029`) that disallows certain compound comparisons.

As [suggested](https://github.com/astral-sh/ruff/issues/8964#issuecomment-1837194529),

> Arguably we should lint against all compound Compares _except_ the following:
> 
>     * Both compares are `is`: `a is b is c`
> 
>     * Both compares are `==`: `a == b ==c`
> 
>     * Both compares are one of `<`, `<=`: `a <= b < c` (probably the most common use  of compound Compare)
> 
>     * Both compares are one of `>`, `>=`: `a >= b > c`

Not a huge fan of the name I gave it, though. Chose `RUF029` as `RUF028` has been used in a bunch of open PRs.

Closes #8964. 

## Test Plan

`cargo nextest run`

### CODE REVIEW

**Comment by sbrugman** [comment]
This pylint rule is related (to the introduction mostly):
https://pylint.pycqa.org/en/latest/user_guide/messages/refactor/chained-comparison.html

Perhaps you'd be interested to implement it too

**Comment by tjkuson** [comment]
Huh, I thought that was already implemented in Ruff. Thanks for the idea @sbrugman, I'll implement it tomorrow.

**Comment by Skylion007** [comment]
Make sense for this to be a pylint rule more than a RUF rule.

**Comment by tjkuson** [comment]
> Make sense for this to be a pylint rule more than a RUF rule.

I am not aware of there being a corresponding Pylint rule on which to map, is there one?

**Comment by Skylion007** [comment]
Yeah, in RUFF it would be `PLR1716`

**Comment by tjkuson** [comment]
I might be misunderstanding something, sorry. That turns things into compound comparisons (have a PR for that tomorrow). This rule does the opposite. They should be separate rules, no?

**Comment by sbrugman** [comment]
Indeed, I understand it the same way. The current PR implements a new rule that does not exist in pylint (although it would be a good fit there) and thus should be assigned the latest available RUFF code, e.g. RUF029. 

The PLR1716 is the linked related rule that is included by Pylint, but not implemented in the PR.

**Comment by Skylion007** [comment]
Ah you are right, my bad.

**Comment by MichaReiser** [comment]
I'm undecided how we should categorize this rule. To me it's a restriction rule because it disallows a subset of Python's grammar. However, I could also see that the rule fits into suspicious because the code probably doesn't do what you intended.  @AlexWaygood what do you think?

**Comment by AlexWaygood** [comment]
I think it's a useful rule to enforce a Python style that's more readable, but I'd certainly agree that it should be disabled by default.

**Comment by MichaReiser** [comment]
Thank you @tjkuson for working on this rule and sorry for the late feedback. 

We agree that the rule itself is valuable and think it should be added to Ruff eventually. But we don't feel comfortable doing it today before #1774 is merged. The rule restricts the allowed Python syntax in an opinionated way, which we aren't comfortable enabling by default but all users that use `RUFF` or `ALL` today would automatically opt in to the rule. 

That's why we want to hold back with the rule for now but hope to get back to it after #1774 is completed. Sorry that we only decided this after you implemented the rule (without mentioning on the issue)

**Comment by tjkuson** [comment]
@MichaReiser No worries!

**Pull request closed without merging**
