### PR TITLE
allow human-friendly rule names in noqa directives

### PR DESCRIPTION
**Pull request by Humandoodlebug**
## Summary

Works towards #1773.

Allows users to write noqa directives with human-friendly rule names. Users can write noqa directives with a comma-separated list of rule names (`# noqa: ambiguous-variable-name , unused-variable`), or even a mix of codes and names (`# noqa: E741, unused-variable`).

Additionally, rules have been added for enforcing the exclusive use of either codes or names, with fixes defined for both.

This is a changeset we are looking to use internally at Pexip. We have been migrating from pylint to ruff, but had pushback due to codes being required for noqa directives (pylint allows human-friendly rule names here). We'd like to upstream these changes, but are aware you may wish to implement some or all of this differently, so we're submitting this as a draft PR for feedback.

## Caveats

We made some compromises with the parsing rules for noqa directives that reference rules by name to avoid confusing comments with rule names. The most significant one is that lists of rule names must be comma separated, which allows us to determine if the next word is supposed to be a rule name or is just a comment. This stricter lexing rule does not apply to lists of rule codes. (so `# noqa: E741 F841` is still fine).

We also require a rule name to be followed by either a comma or a whitespace character (or the end of the line). This prevents us from seeing e.g. `some_rule_name` and interpreting it as a rule named `some` followed by a comment `_rule_name`.

## Test Plan

- Updated existing noqa snapshot tests and added new ones to cover using rule names.
- Added snapshot tests for new `RUF102` (`noqa-by-code`) and `RUF103` (`noqa-by-name`) lints.

### CODE REVIEW

**Comment by kaddkaka** [comment]
Does this PR support multiple names per rule as suggested in https://github.com/astral-sh/ruff/issues/1773#issuecomment-2163951669 ?

**Comment by kaddkaka** [comment]
does all rules already have names today o?

**Comment by kaddkaka** [comment]
- `RUF102` (noqa-by-code) warns if code is used.  
- `RUF103` (noqa-by-name) warns if name is used.  

Is there any request to have RUF103? Is it valuable to have?

**Comment by MichaReiser** [comment]
Thanks, @Humandoodlebug, for working on this. I'll close this PR because of inactivity, and I also think it requires some design work: For example, do we want to extend `noqa` comments, or should we introduce a ruff-specific ignore comment (e.g., `ruff: ignore[code]`) that allows human-readable names? I also don't think that we should allow mixing both codes and rule names.
Thanks again for exploring adding human readable names. This PR is a great inspiration.

**Comment by MichaelOultram** [comment]
I was working to rebase in the background for @Humandoodlebug, but work/life commitments kept getting in the way.

As we mentioned in the first post, we are perfectly happy for the ruff project to take a different approach here. We at Pexip developed this patch for our specific internal needs, and decided to share based on the interest in #1773.

I'm glad the PR has given at least some inspiration, and closing seems like the right choice given the design work required.

We at Pexip will continue to use the patch internally for now. When this feature is reworked and added to ruff properly, we will migrate over and ditch our patch.

**Pull request closed without merging**
