### PR TITLE
Render Markdown output from `ruff rule`

### PR DESCRIPTION
**Pull request by cjolowicz**
## Summary

See https://github.com/astral-sh/ruff/issues/2938#issuecomment-1509755352

This is a partial revert of #2959 with adaptations for the new API.

## Test Plan

```console
$ ruff rule B006
$ ruff rule --all
```

Screenshot 2023-10-23 at 01 53 30

### CODE REVIEW

**Comment by cjolowicz** [comment]
Needs rerun of snapshot in 80x25 terminal I think...

**Comment by cjolowicz** [comment]
Just a thought: An alternative approach would be to allow users to configure a Markdown processor in _pyproject.toml_ or _ruff.toml_. Something like this:

```toml
[tool.ruff]
markdown-processor = "mdcat"
#markdown-processor = "mdcat --columns=72"
#markdown-processor = "rich --markdown --width=72 -"
#markdown-processor = "bat --plain --language=md"
```

Pros:
- any processor you like
- no dependencies on Ruff
- users can pass options

Cons:
- user has to install and configure the processor

**Comment by MichaReiser** [comment]
What syntax does pulldown markdown support? I've run into issues where our website didn't support the markdown used. It would get more challenging if pulldown markdown adds further restrictions.

**Comment by zanieb** [comment]
It looks like there hasn't been any activity on this in a while. It seems like we need to have more discussion about the design before we can accept a pull request. Thank you!

**Pull request closed without merging**
